"""Delta DDL for the active four-task GSO workflow."""

from genie_space_optimizer.common.config import (
    TABLE_ARTIFACTS,
    TABLE_BENCHMARK_MUTATIONS,
    TABLE_ITERATIONS,
    TABLE_MV_CANDIDATES,
    TABLE_MV_CONSENTS,
    TABLE_MV_CREATED_OBJECTS,
    TABLE_PATCHES,
    TABLE_RUNS,
    TABLE_STAGES,
)

_GENIE_OPT_RUNS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_runs (
    run_id              STRING        NOT NULL COMMENT 'UUID for this optimization run',
    space_id            STRING        NOT NULL COMMENT 'Genie Agent ID being optimized',
    domain              STRING        NOT NULL COMMENT 'Domain name (e.g. revenue_property)',
    catalog             STRING        NOT NULL COMMENT 'Unity Catalog name',
    uc_schema           STRING        NOT NULL COMMENT 'UC schema (catalog.schema format)',
    status              STRING        NOT NULL COMMENT 'QUEUED|IN_PROGRESS|CONVERGED|STALLED|MAX_ITERATIONS|FAILED|CANCELLED|SKIPPED|MV_ADVICE (MV-D23 terminal-at-birth advice run)',
    started_at          TIMESTAMP     NOT NULL COMMENT 'When the run was created',
    completed_at        TIMESTAMP              COMMENT 'When the run reached a terminal state',
    job_run_id          STRING                 COMMENT 'Databricks Job run ID',
    job_id              STRING                 COMMENT 'Databricks Job definition ID',
    max_iterations      INT           NOT NULL COMMENT 'Maximum lever iterations allowed',
    levers              STRING        NOT NULL COMMENT 'JSON array of lever numbers to try, e.g. [1,2,3,4,5]',
    apply_mode          STRING        NOT NULL COMMENT 'Where patches are applied: genie_config|uc_artifact|both',
    llm_model           STRING                 COMMENT 'Databricks Model Serving endpoint selected for this optimization run',
    benchmark_policy    STRING                 COMMENT 'Benchmark handling policy: review_only|repair_allowed',
    benchmark_mutation_count INT                COMMENT 'Number of live benchmark additions or SQL updates performed by this run',
    deploy_target       STRING                 COMMENT 'DABs target for post-optimization deploy (null = no deploy)',
    benchmarks_generated BOOLEAN                COMMENT 'True if benchmarks were auto-generated by LLM during this run',
    best_iteration      INT                    COMMENT 'Iteration number with highest accuracy',
    best_accuracy       DOUBLE                 COMMENT 'Best overall accuracy achieved (0-100)',
    convergence_reason  STRING                 COMMENT 'Why the run stopped (threshold_met|plateau|max_iterations|error)',
    config_snapshot     STRING                 COMMENT 'JSON: Genie Agent config at run start',
    triggered_by        STRING                 COMMENT 'User email who initiated the run',
    warehouse_id        STRING                 COMMENT 'SQL warehouse ID resolved at preflight; used by lever_loop / finalize / deploy as a Delta-fallback for the preflight taskValue when Repair Run drops in-memory state',
    max_benchmark_count INT                    COMMENT 'Effective max benchmark count computed by preflight; Delta-fallback for the preflight.max_benchmark_count taskValue',
    updated_at          TIMESTAMP     NOT NULL COMMENT 'Last update timestamp'
)
USING DELTA
PARTITIONED BY (space_id)
COMMENT 'Genie Agent optimization runs - one row per optimization attempt'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_STAGES_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_stages (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    task_key            STRING                 COMMENT 'Databricks Job task key (preflight, baseline_eval, lever_loop, finalize, deploy)',
    stage               STRING        NOT NULL COMMENT 'Stage name (PREFLIGHT_STARTED, LEVER_2_EVAL_DONE, etc.)',
    status              STRING        NOT NULL COMMENT 'STARTED|COMPLETE|FAILED|SKIPPED|ROLLED_BACK',
    started_at          TIMESTAMP     NOT NULL COMMENT 'When this stage began',
    completed_at        TIMESTAMP              COMMENT 'When this stage ended (null if in progress)',
    duration_seconds    DOUBLE                 COMMENT 'Wall-clock duration of this stage',
    lever               INT                    COMMENT 'Lever number (1-5) if this is a lever stage, null otherwise',
    iteration           INT                    COMMENT 'Evaluation iteration number if applicable',
    detail_json         STRING                 COMMENT 'JSON: stage-specific detail',
    error_message       STRING                 COMMENT 'Error message if status=FAILED'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Optimization stage transitions - ordered timeline of what happened'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_ITERATIONS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_iterations (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL COMMENT 'Evaluation iteration number (0 = baseline)',
    lever               INT                    COMMENT 'Which lever was applied before this eval (null for baseline)',
    eval_scope          STRING        NOT NULL COMMENT 'full|enrichment',
    timestamp           TIMESTAMP     NOT NULL COMMENT 'When this evaluation completed',
    overall_accuracy    DOUBLE        NOT NULL COMMENT 'Overall accuracy percentage (0-100)',
    total_questions     INT           NOT NULL COMMENT 'Number of benchmark questions evaluated',
    correct_count       INT           NOT NULL COMMENT 'Number of questions that passed all judges',
    scores_json         STRING        NOT NULL COMMENT 'JSON: per-judge scores',
    failures_json       STRING                 COMMENT 'JSON: array of failed question IDs',
    remaining_failures  STRING                 COMMENT 'JSON: array of question IDs still failing',
    thresholds_met      BOOLEAN       NOT NULL COMMENT 'True if all quality thresholds passed',
    rows_json           STRING                 COMMENT 'JSON: per-question evaluation detail rows',
    reflection_json     STRING                 COMMENT 'JSON: adaptive loop reflection entry for this iteration',
    evaluated_count     INT                    COMMENT 'Denominator of overall_accuracy (total_questions minus runtime exclusions; see Bug #2 denominator contract)',
    excluded_count      INT                    COMMENT 'Number of rows removed from the denominator at runtime (ground-truth excluded, both empty, Genie unavailable, temporally stale, etc.)',
    rolled_back         BOOLEAN       DEFAULT false COMMENT 'Tier 1.1: true if this iteration was rolled back by the accept/rollback gate. Readers that represent current state must filter this out (see _get_baseline_and_best_accuracy, promote_best_model, load_latest_full_iteration).',
    rolled_back_at      TIMESTAMP              COMMENT 'Tier 1.1: timestamp of rollback',
    rollback_reason     STRING                 COMMENT 'Tier 1.1: human-readable rollback reason (mirrors genie_opt_patches.rollback_reason)',
    config_json         STRING                 COMMENT 'GSO v2 Phase 4 (D3): JSON of the submitted/local Genie Agent config for THIS iteration (baseline iter 0, patch/eval iterations 1..N). Whitelisted Genie-domain projection (optimizer-internal _* keys dropped).',
    observed_config_json STRING                COMMENT 'Authoritative serialized_space returned by GET include_serialized_space=true after the config was persisted. NULL means the API read-back was unavailable; consumers must not infer external drift from the submitted config alone.',
    is_champion         BOOLEAN       DEFAULT false COMMENT 'GSO v2 Phase 4 (D3): true on the single champion iteration row (the best iteration as chosen by the existing Delta-driven selection in promote_best_model). Marked in Delta only — NO UC model registration.',
    num_needs_review    INT                    COMMENT 'Count of per-question rows whose official assessment is NEEDS_REVIEW (neither GOOD nor BAD).',
    eval_run_id         STRING                 COMMENT 'GSO v2 Phase 6: native Genie benchmark eval-run id for this iteration (from the official EvalRunner). Surfaced so the UI can reference the underlying eval run. NULL on the legacy in-process path.',
    eval_run_status     STRING                 COMMENT 'GSO v2 Phase 6: native eval-run terminal status (e.g. DONE / EVALUATION_FAILED / CANCELLED) for this iteration. NULL on the legacy in-process path.',
    attempt_no          INT                    COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): monotonic display counter for the optimize loop — 0=baseline, 1..N=LLM patch/eval attempts.',
    attempt_mode        STRING                 COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): baseline or llm_patch.',
    best_accuracy       DOUBLE                 COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): best full-benchmark accuracy seen so far at the end of this attempt (the champion staircase value).',
    best_config_version_id STRING              COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): serialized config snapshot reference for the current champion.',
    current_hypothesis  STRING                 COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): JSON of the active patch hypothesis tested in this attempt.',
    do_not_repeat       STRING                 COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): JSON ARRAY of rejected lever families / strategies the controller will not retry.',
    terminal_reason     STRING                 COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): TARGET_REACHED | MAX_ATTEMPTS | NO_NEW_HYPOTHESIS | EVAL_INVALID | CONFIG_VALIDATION_FAILED | LOOP_STATE_INVALID | EVAL_BUDGET_EXHAUSTED. Set on the champion row only.',
    decision            STRING                 COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): per-attempt aggregate decision — accept | reject | continue.',
    decision_reason     STRING                 COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): human-readable reason for the decision (e.g. rolled_back (Δacc<0), no_enrichment_candidates).',
    surgical_attempts_used INT                 COMMENT 'GSO v2 Phase 8 (loop-state, arch §7.4): patch/eval attempt budget consumed so far.',
    next_hypothesis     STRING                 COMMENT 'GSO v2 Phase 8 (loop-state, arch §7.4): JSON of the next patch idea the controller chose from the residual failures.',
    target_accuracy     DOUBLE                 COMMENT 'GSO v2 Phase 8 (loop-state, arch §7.4): stop-early target accuracy in force for this run (0-100 scale; default 90.0).',
    max_attempts        INT                    COMMENT 'GSO v2 Phase 8 (loop-state, arch §7.4): patch/eval attempt budget in force for this run (default 3).'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Evaluation iteration results - scores and failures per eval pass'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true',
    'delta.feature.allowColumnDefaults' = 'supported'
)"""

_GENIE_OPT_PATCHES_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_patches (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL COMMENT 'Iteration when this patch was applied',
    lever               INT           NOT NULL COMMENT 'Lever number (1-5)',
    patch_index         INT           NOT NULL COMMENT 'Index within the patch set',
    patch_type          STRING        NOT NULL COMMENT 'Patch type from PATCH_TYPES',
    scope               STRING        NOT NULL COMMENT 'genie_config or uc_artifact or both',
    risk_level          STRING        NOT NULL COMMENT 'low|medium|high',
    target_object       STRING                 COMMENT 'Object being modified (table name, column name, etc.)',
    patch_json          STRING        NOT NULL COMMENT 'JSON: full patch definition',
    command_json        STRING                 COMMENT 'JSON: rendered action command',
    rollback_json       STRING                 COMMENT 'JSON: rollback command',
    applied_at          TIMESTAMP     NOT NULL COMMENT 'When the patch was applied',
    rolled_back         BOOLEAN                COMMENT 'True if this patch was subsequently rolled back',
    rolled_back_at      TIMESTAMP              COMMENT 'When the rollback occurred',
    rollback_reason     STRING                 COMMENT 'Why the patch was rolled back',
    proposal_id         STRING                 COMMENT 'FK to the proposal that generated this patch',
    cluster_id          STRING                 COMMENT 'Failure cluster that motivated this patch',
    provenance_json     STRING                 COMMENT 'JSON: full provenance chain from judge verdicts to this patch'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Patch audit trail - every metadata change applied to Genie Agent'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_BENCHMARK_MUTATIONS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_benchmark_mutations (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    question_id         STRING        NOT NULL COMMENT 'Benchmark question id the mutation applies to',
    op                  STRING        NOT NULL COMMENT 'added | excluded (run-local, non-mutating) | removed (legacy) | changed | prune_recommended (advisory, non-mutating)',
    before              STRING                 COMMENT 'JSON {question, sql} prior state (NULL for added)',
    after               STRING                 COMMENT 'JSON {question, sql} resulting state (unchanged for excluded; NULL for removed / prune_recommended)',
    reason              STRING                 COMMENT 'Why GSO recorded this row (preflight_push | repair_exhausted | over_window_recommendation | ...)',
    logged_at           TIMESTAMP     NOT NULL COMMENT 'When this mutation was recorded'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'GSO v2 provenance ledger — live benchmark additions/changes plus run-local exclusions and prune recommendations'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_ARTIFACTS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_artifacts (
    artifact_id         STRING        NOT NULL COMMENT 'UUID for this artifact row',
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    stage_name          STRING                 COMMENT 'Notebook or stage that wrote the artifact (intake_and_snapshot, benchmark_qc_and_repair, ...)',
    iteration           INT                    COMMENT 'Iteration number, when applicable (NULL for run-level artifacts)',
    artifact_kind       STRING        NOT NULL COMMENT 'run_manifest | wide_schema_inventory | wide_schema_evidence | wide_schema_selection_plan | wide_schema_profile_telemetry | wide_schema_prompt_telemetry | wide_schema_audit | space_metadata | benchmark_qc | space_quality_enrichment | publish_record | mv_candidate_ddl',
    artifact_json       STRING                 COMMENT 'JSON payload for the artifact (enough to reconstruct the pass without notebook-local state)',
    content_hash        STRING                 COMMENT 'Hash of artifact_json for dedupe / idempotency / replay safety',
    parent_artifact_id  STRING                 COMMENT 'Lineage pointer to the artifact this one derives from',
    source_notebook     STRING                 COMMENT 'Notebook name that produced the row',
    created_at          TIMESTAMP     NOT NULL COMMENT 'Write timestamp'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'GSO v2 generic Delta handoff table for stage-level JSON blobs, including immutable wide-schema inventory and append-only selection-plan revisions'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_MV_CANDIDATES_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_mv_candidates (
    dedup_fingerprint   STRING        NOT NULL COMMENT 'MV-D7 idempotency key: sha256(space_id | canonical_measure_expr | sorted_source_set). Upsert key together with target_space_id; also the content_hash of the rendered-DDL genie_opt_artifacts row for this candidate',
    target_space_id     STRING        NOT NULL COMMENT 'Genie Agent the candidate is proposed for',
    suggestion_id       STRING        NOT NULL COMMENT 'Stable proposal id surfaced to the UI and carried on approve/reject decisions',
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id — the run whose advisor phase last proposed or refreshed this candidate. A candidate outlives it (MV-D1)',
    candidate_type      STRING        NOT NULL COMMENT 'NEW_METRIC_VIEW|REPLACE_RAW_TABLE|ADD_MEASURE|CONFLICT (POV Part 4 proposal `type`)',
    confidence_score    DOUBLE                 COMMENT 'Weighted L/Y/S/D score, 0-100',
    tier                STRING                 COMMENT 'HIGH|MEDIUM|LOW confidence tier',
    proposed_object     STRING                 COMMENT 'Fully-qualified target name for the metric view (catalog.schema.name)',
    score_components_json STRING               COMMENT 'JSON: POV Part 4 `score_components` — per-signal scores plus the weights used',
    evidence_json       STRING                 COMMENT 'JSON: POV Part 4 `evidence` — fingerprint recurrence, benchmark question ids, statement ids, lineage source tables, semantic top match',
    provenance_json     STRING                 COMMENT 'JSON: POV Part 4 `provenance` — generated_by, auth_identity, gso_run_id, generated_at',
    alternatives_json   STRING                 COMMENT 'JSON: POV Part 4 `alternatives` — ranked runner-up shapes for the same fingerprint',
    conflicts_json      STRING                 COMMENT 'JSON: POV Part 4 `conflicts` — existing instructions or trusted assets defining the same concept differently. Non-empty means human adjudication is required and the candidate is never auto-resolved',
    requested_mode      STRING                 COMMENT 'mv_action_mode the user asked for on the proposing run: suggest_only|create_and_attach|sandbox',
    effective_mode      STRING                 COMMENT 'Mode actually in force after entitlement/consent re-verification. Never upgrades relative to requested_mode',
    decision            STRING                 COMMENT 'Human decision: NULL (undecided) | approved | rejected',
    decided_by          STRING                 COMMENT 'User email who approved or rejected the candidate',
    decided_at          TIMESTAMP              COMMENT 'When the decision was recorded',
    suppressed_until    TIMESTAMP              COMMENT 'Rejection decay window — the advisor must not re-surface this fingerprint before this timestamp',
    approved_for_rerun  BOOLEAN       DEFAULT false COMMENT 'MV-D1: true only when an approved candidate is eligible to be created under OBO on a subsequent run. create_and_attach is gated on this flag',
    created_at          TIMESTAMP     NOT NULL COMMENT 'When the candidate was first proposed',
    updated_at          TIMESTAMP     NOT NULL COMMENT 'Last upsert timestamp — a later run re-proposing the same fingerprint refreshes this'
)
USING DELTA
PARTITIONED BY (target_space_id)
COMMENT 'Metric view advisor proposals (MV-D7) - one row per (target_space_id, dedup_fingerprint), upserted so re-runs never duplicate a candidate'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true',
    'delta.feature.allowColumnDefaults' = 'supported'
)"""

_GENIE_OPT_MV_CONSENTS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_mv_consents (
    probe_id            STRING        NOT NULL COMMENT 'Entitlement probe id — the upsert key. Issued by the OBO probe route before any run exists',
    run_id              STRING                 COMMENT 'FK to genie_opt_runs.run_id, NULL until the consent is carried into a run at trigger time. This is why the table is unpartitioned',
    granted_by          STRING        NOT NULL COMMENT 'User email who granted consent — the identity every OBO write for this run executes under',
    granted_at          TIMESTAMP     NOT NULL COMMENT 'When consent was granted',
    target_catalog      STRING        NOT NULL COMMENT 'Consented Unity Catalog catalog. Writes go here and nowhere else',
    target_schema       STRING        NOT NULL COMMENT 'Consented UC schema. A failed write is a downgrade, never a retry somewhere more permissive',
    materialize_consented BOOLEAN     DEFAULT false COMMENT 'Separate consent for materialization (mv_materialize) — never bundled with create or attach',
    probe_results_json  STRING                 COMMENT 'JSON: probe verdict detail — checked_as, effective privileges, runtime capability rows (MV-D8 DBR floors), missing privileges, remediation GRANT',
    verdict             STRING                 COMMENT 'SUFFICIENT|INSUFFICIENT|UNKNOWN',
    reverified_at_trigger TIMESTAMP            COMMENT 'When the probe was last re-verified immediately before an OBO write. NULL means never re-verified; the job refuses to attach without it',
    downgrade_reason    STRING                 COMMENT 'Why the run was downgraded to suggest_only, if it was. Downgrade never upgrades',
    updated_at          TIMESTAMP     NOT NULL COMMENT 'Last upsert timestamp'
)
USING DELTA
COMMENT 'Metric view entitlement probes and consent decisions (MV-D7) - one row per probe_id; the audit answer to "who authorized this metric view and against what privileges"'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true',
    'delta.feature.allowColumnDefaults' = 'supported'
)"""

_GENIE_OPT_MV_CREATED_OBJECTS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_mv_created_objects (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id — the run this object was created for and attached by',
    suggestion_id       STRING        NOT NULL COMMENT 'FK to genie_opt_mv_candidates.suggestion_id the object was created from. Upsert key together with run_id',
    full_name           STRING        NOT NULL COMMENT 'Fully-qualified name of the created metric view (catalog.schema.name), in the consented schema only',
    created_by          STRING        NOT NULL COMMENT 'Identity that executed CREATE VIEW ... WITH METRICS. Always the consenting user under OBO — never the service principal',
    created_at          TIMESTAMP     NOT NULL COMMENT 'When the UC object was created by the backend, before the job was submitted',
    attach_patch_id     STRING                 COMMENT 'FK to the genie_opt_patches row that attached this view to data_sources.metric_views',
    baseline_eval_run_id STRING                COMMENT 'Native eval-run id measured with the view created but NOT yet attached',
    post_attach_eval_run_id STRING             COMMENT 'Native eval-run id measured immediately after the attach patch, before any lever fires. The delta against baseline_eval_run_id is the isolated metric-view lift',
    status              STRING        NOT NULL COMMENT 'CREATED|ATTACHED|DETACHED|DROPPED',
    on_regression_action STRING                COMMENT 'DETACH_ONLY_NEVER_DROP outside sandbox mode; SANDBOX_AUTO_DROP only for a scratch schema that exists solely for the run',
    updated_at          TIMESTAMP     NOT NULL COMMENT 'Last upsert timestamp - moves with every status transition',
    lift_report_json    STRING                 COMMENT 'JSON: eval_runner.LiftReport.to_dict() verbatim, comparing baseline_eval_run_id against post_attach_eval_run_id. The isolated metric-view lift, and the evidence for a DETACHED verdict'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Metric views created under OBO for a run and their attach/detach lifecycle (MV-D7) - one row per (run_id, suggestion_id). The UC object is never auto-dropped outside sandbox mode'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_ALL_DDL: dict[str, str] = {
    TABLE_RUNS: _GENIE_OPT_RUNS_DDL,
    TABLE_STAGES: _GENIE_OPT_STAGES_DDL,
    TABLE_ITERATIONS: _GENIE_OPT_ITERATIONS_DDL,
    TABLE_PATCHES: _GENIE_OPT_PATCHES_DDL,
    TABLE_BENCHMARK_MUTATIONS: _GENIE_OPT_BENCHMARK_MUTATIONS_DDL,
    TABLE_ARTIFACTS: _GENIE_OPT_ARTIFACTS_DDL,
    TABLE_MV_CANDIDATES: _GENIE_OPT_MV_CANDIDATES_DDL,
    TABLE_MV_CONSENTS: _GENIE_OPT_MV_CONSENTS_DDL,
    TABLE_MV_CREATED_OBJECTS: _GENIE_OPT_MV_CREATED_OBJECTS_DDL,
}

ADDITIVE_COLUMN_MIGRATIONS: tuple[tuple[str, str, str], ...] = (
    (TABLE_RUNS, "job_id", "STRING COMMENT 'Databricks Job definition ID'"),
    (TABLE_PATCHES, "provenance_json", "STRING COMMENT 'JSON: full provenance chain from judge verdicts to this patch'"),
    (TABLE_RUNS, "llm_model", "STRING COMMENT 'Databricks Model Serving endpoint selected for this optimization run'"),
    (TABLE_RUNS, "benchmark_policy", "STRING COMMENT 'Benchmark handling policy: review_only|repair_allowed'"),
    (TABLE_RUNS, "benchmark_mutation_count", "INT COMMENT 'Number of live benchmark additions or SQL updates performed by this run'"),
    (TABLE_ITERATIONS, "reflection_json", "STRING COMMENT 'JSON: adaptive loop reflection entry for this iteration'"),
    (TABLE_ITERATIONS, "evaluated_count", "INT COMMENT 'Denominator of overall_accuracy (total_questions minus runtime exclusions; see Bug #2 denominator contract)'"),
    (TABLE_ITERATIONS, "excluded_count", "INT COMMENT 'Number of rows removed from the denominator at runtime (ground-truth excluded, both empty, Genie unavailable, temporally stale, etc.)'"),
    (TABLE_ITERATIONS, "rolled_back", "BOOLEAN DEFAULT false COMMENT 'Tier 1.1: true if this iteration was rolled back by the accept/rollback gate. Readers that represent current state must filter this out (see _get_baseline_and_best_accuracy, promote_best_model, load_latest_full_iteration).'"),
    (TABLE_ITERATIONS, "rolled_back_at", "TIMESTAMP COMMENT 'Tier 1.1: timestamp of rollback'"),
    (TABLE_ITERATIONS, "rollback_reason", "STRING COMMENT 'Tier 1.1: human-readable rollback reason (mirrors genie_opt_patches.rollback_reason)'"),
    (TABLE_PATCHES, "applied_patch_type", "STRING COMMENT 'T2.13: actual patch_type that was applied after any applier-side transformations (e.g. update_instruction_section emitted by the rewrite_instruction downgrade splitter). May differ from patch_type (the proposal type).'"),
    (TABLE_PATCHES, "applied_patch_detail", "STRING COMMENT 'T2.13: human-readable detail describing the applied transformation (e.g. section_name for update_instruction_section, or a note when a rewrite_instruction was split into children).'"),
    (TABLE_RUNS, "warehouse_id", "STRING COMMENT 'SQL warehouse ID resolved at preflight; Delta-fallback for the preflight.warehouse_id taskValue'"),
    (TABLE_RUNS, "max_benchmark_count", "INT COMMENT 'Effective max benchmark count; Delta-fallback for the preflight.max_benchmark_count taskValue'"),
    (TABLE_ITERATIONS, "config_json", "STRING COMMENT 'GSO v2 Phase 4 (D3): JSON of the submitted/local Genie Agent config for this iteration. Whitelisted Genie-domain projection (optimizer-internal _* keys dropped).'"),
    (TABLE_ITERATIONS, "observed_config_json", "STRING COMMENT 'Authoritative serialized_space returned by GET include_serialized_space=true after persistence. NULL means API read-back was unavailable; do not infer drift from config_json alone.'"),
    (TABLE_ITERATIONS, "is_champion", "BOOLEAN DEFAULT false COMMENT 'GSO v2 Phase 4 (D3): true on the single champion iteration row (best iteration per the existing Delta-driven selection in promote_best_model). Marked in Delta only — NO UC model registration.'"),
    (TABLE_ITERATIONS, "num_needs_review", "INT COMMENT 'Count of per-question rows whose official assessment is NEEDS_REVIEW.'"),
    (TABLE_ITERATIONS, "eval_run_id", "STRING COMMENT 'GSO v2 Phase 6: native Genie benchmark eval-run id for this iteration (from the official EvalRunner). NULL on the legacy in-process path.'"),
    (TABLE_ITERATIONS, "eval_run_status", "STRING COMMENT 'GSO v2 Phase 6: native eval-run terminal status (DONE / EVALUATION_FAILED / CANCELLED). NULL on the legacy in-process path.'"),
    # GSO v2 Phase 7 (loop-state, arch §7.4): genie_opt_iterations is the
    # single per-attempt truth — extend it with the controller loop-state
    # columns alongside the Phase-4 config_json/is_champion. The unified
    # optimize loop writes these for baseline + each LLM patch/eval attempt.
    (TABLE_ITERATIONS, "attempt_no", "INT COMMENT 'GSO v2 Phase 7 (loop-state): monotonic display counter — 0=baseline, 1..N=LLM patch/eval attempts.'"),
    (TABLE_ITERATIONS, "attempt_mode", "STRING COMMENT 'GSO v2 Phase 7 (loop-state): baseline or llm_patch.'"),
    (TABLE_ITERATIONS, "best_accuracy", "DOUBLE COMMENT 'GSO v2 Phase 7 (loop-state): best full-benchmark accuracy so far (champion staircase value).'"),
    (TABLE_ITERATIONS, "best_config_version_id", "STRING COMMENT 'GSO v2 Phase 7 (loop-state): serialized config snapshot reference for the current champion.'"),
    (TABLE_ITERATIONS, "current_hypothesis", "STRING COMMENT 'GSO v2 Phase 7 (loop-state): JSON of the active patch hypothesis tested in this attempt.'"),
    (TABLE_ITERATIONS, "do_not_repeat", "STRING COMMENT 'GSO v2 Phase 7 (loop-state): JSON ARRAY of rejected lever families / strategies.'"),
    (TABLE_ITERATIONS, "terminal_reason", "STRING COMMENT 'GSO v2 Phase 7 (loop-state): TARGET_REACHED | MAX_ATTEMPTS | NO_NEW_HYPOTHESIS | EVAL_INVALID | CONFIG_VALIDATION_FAILED | LOOP_STATE_INVALID | EVAL_BUDGET_EXHAUSTED.'"),
    (TABLE_ITERATIONS, "decision", "STRING COMMENT 'GSO v2 Phase 7 (loop-state): per-attempt aggregate decision — accept | reject | continue.'"),
    (TABLE_ITERATIONS, "decision_reason", "STRING COMMENT 'GSO v2 Phase 7 (loop-state): human-readable reason for the decision.'"),
    # GSO v2 Phase 8 (loop-state, arch §7.4): the unified optimize loop adds
    # the consumed-attempt counter, next-hypothesis pointer, and the two run-level
    # stop knobs (target_accuracy / max_attempts) as per-attempt columns so the
    # Attempt Ladder/Ledger and resume read one self-describing row.
    (TABLE_ITERATIONS, "surgical_attempts_used", "INT COMMENT 'GSO v2 Phase 8 (loop-state): patch/eval attempt budget consumed so far.'"),
    (TABLE_ITERATIONS, "next_hypothesis", "STRING COMMENT 'GSO v2 Phase 8 (loop-state): JSON of the next patch idea chosen by the controller from residual failures.'"),
    (TABLE_ITERATIONS, "target_accuracy", "DOUBLE COMMENT 'GSO v2 Phase 8 (loop-state): stop-early target accuracy in force (0-100 scale; default 90.0).'"),
    (TABLE_ITERATIONS, "max_attempts", "INT COMMENT 'GSO v2 Phase 8 (loop-state): patch/eval attempt budget in force (default 3).'"),
    # MV-D7 deferred this column to the prompt that produces a lift report; it
    # lands with the attach/lift phase (MV-D16) so existing tables gain it in
    # place rather than needing a recreate.
    (TABLE_MV_CREATED_OBJECTS, "lift_report_json", "STRING COMMENT 'JSON: eval_runner.LiftReport.to_dict() verbatim for the isolated metric-view lift.'"),
    # MV-D23: the sentinel advice-run discriminator. Added WITHOUT a DEFAULT
    # because genie_opt_runs does not enable allowColumnDefaults; every reader
    # treats NULL as 'optimization' (COALESCE), and the exclusion predicate is
    # the single pinned MV_ADVICE_RUN_EXCLUSION constant (common/config.py), not
    # a per-caller convention. Standalone advice runs are born terminal
    # (status=MV_ADVICE) so active-run reconciliation never picks one up.
    (TABLE_RUNS, "run_kind", "STRING COMMENT 'MV-D23: optimization (default; NULL is treated as optimization) | mv_advice (a standalone metric-view advice request that never ran an eval). Advice runs are excluded from run-history and accuracy aggregates via the MV_ADVICE_RUN_EXCLUSION predicate.'"),
    # MV-D23: the rendered replay body on the candidate row, so the MV-D22
    # create path no longer depends on the run-partitioned mv_candidate_ddl
    # artifact. The in-job advisor keeps writing the artifact byte-unchanged;
    # the standalone (no-run) advisor writes yaml_text here, and
    # mv_create._load_ddl_artifact falls back to it.
    (TABLE_MV_CANDIDATES, "yaml_text", "STRING COMMENT 'MV-D23: the immutable rendered metric-view YAML body for this candidate (MV-D22 replay source), so a standalone advice candidate is replayable without a run-partitioned genie_opt_artifacts row.'"),
    # MV-D24: the create-path discriminator. NULL/OBO_CREATED = the backend
    # created it under OBO; USER_CREATED = a bring-your-own view the user
    # created and registered. The drop route refuses USER_CREATED on provenance
    # (before the status check), and mv_attach relaxes its created_by identity
    # guard only for USER_CREATED rows.
    (TABLE_MV_CREATED_OBJECTS, "provenance", "STRING COMMENT 'MV-D24: OBO_CREATED (default; NULL treated as OBO_CREATED) | USER_CREATED. The app never drops a USER_CREATED view.'"),
)
