"""DDL constants for GSO optimization Delta tables.

Extracted into a standalone module so that deploy scripts (e.g.
``scripts/grant_permissions.py``) can import ``_ALL_DDL`` without
pulling in pandas or other heavy runtime dependencies.
"""

from genie_space_optimizer.common.config import (
    TABLE_ARTIFACTS,
    TABLE_ASI,
    TABLE_BENCHMARK_MUTATIONS,
    TABLE_FINALIZE_ATTESTATION,
    TABLE_ITERATIONS,
    TABLE_PATCHES,
    TABLE_PROVENANCE,
    TABLE_RUNS,
    TABLE_STAGES,
    TABLE_SUGGESTIONS,
)

# ── Table Names (not in common/config.py) ─────────────────────────────

TABLE_DATA_ACCESS_GRANTS = "genie_opt_data_access_grants"

# Task 1: Ground-truth correction queue.
# When the arbiter rules ``genie_correct`` on a row whose
# ``result_correctness`` is ``no``, the GT itself is wrong or
# under-specified; the row is parked here for human/automated review
# rather than driving the lever loop.
TABLE_GT_CORRECTION_CANDIDATES = "genie_eval_gt_correction_candidates"

# Task 3: Decision audit. Single Delta surface for every gate decision
# (acceptance, proposal grounding, reflection drops, AFS / leakage
# rejections, etc.). Carries source_cluster_ids_json and
# proposal_to_patch_map_json so a single SQL query reconstructs
# cluster -> proposal -> patch -> applied -> accepted/rolled_back.
TABLE_LEVER_LOOP_DECISIONS = "genie_eval_lever_loop_decisions"

# Task 4: Per-question pass/fail transition tracker. Persisted full-eval
# transitions so a bundle that flips a previously-passing qid from pass
# to fail rolls back regardless of aggregate direction.
TABLE_QUESTION_REGRESSIONS = "genie_eval_question_regressions"

# Task 8: Human-required escalation queue. After a cluster's signature
# accumulates ``HUMAN_REQUIRED_CONTENT_ROLLBACK_THRESHOLD`` content
# regressions in the same run, the optimizer stops proposing patches
# for it and parks an evidence record here for human review.
TABLE_HUMAN_REQUIRED = "genie_eval_human_required"

# Task 9: proactive feature-mining artifacts. Persisted per run so a
# reviewer can inspect "what did the proactive miner find on the
# passing corpus, and what enrichments did it propose?" without
# replaying the run.
TABLE_PROACTIVE_CORPUS_PROFILE = "genie_eval_proactive_corpus_profile"
TABLE_PROACTIVE_PATCHES = "genie_eval_proactive_patches"

# ── DDL Constants ────────────────────────────────────────────────────────

_GENIE_OPT_RUNS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_runs (
    run_id              STRING        NOT NULL COMMENT 'UUID for this optimization run',
    space_id            STRING        NOT NULL COMMENT 'Genie Space ID being optimized',
    domain              STRING        NOT NULL COMMENT 'Domain name (e.g. revenue_property)',
    catalog             STRING        NOT NULL COMMENT 'Unity Catalog name',
    uc_schema           STRING        NOT NULL COMMENT 'UC schema (catalog.schema format)',
    status              STRING        NOT NULL COMMENT 'QUEUED|IN_PROGRESS|CONVERGED|STALLED|MAX_ITERATIONS|FAILED|CANCELLED',
    started_at          TIMESTAMP     NOT NULL COMMENT 'When the run was created',
    completed_at        TIMESTAMP              COMMENT 'When the run reached a terminal state',
    job_run_id          STRING                 COMMENT 'Databricks Job run ID',
    job_id              STRING                 COMMENT 'Databricks Job definition ID',
    max_iterations      INT           NOT NULL COMMENT 'Maximum lever iterations allowed',
    levers              STRING        NOT NULL COMMENT 'JSON array of lever numbers to try, e.g. [1,2,3,4,5]',
    apply_mode          STRING        NOT NULL COMMENT 'Where patches are applied: genie_config|uc_artifact|both',
    llm_model           STRING                 COMMENT 'Databricks Model Serving endpoint selected for this optimization run',
    deploy_target       STRING                 COMMENT 'DABs target for post-optimization deploy (null = no deploy)',
    benchmarks_generated BOOLEAN                COMMENT 'True if benchmarks were auto-generated by LLM during this run',
    best_iteration      INT                    COMMENT 'Iteration number with highest accuracy',
    best_accuracy       DOUBLE                 COMMENT 'Best overall accuracy achieved (0-100)',
    best_repeatability  DOUBLE                 COMMENT 'Best repeatability percentage (0-100)',
    convergence_reason  STRING                 COMMENT 'Why the run stopped (threshold_met|plateau|max_iterations|error)',
    config_snapshot     STRING                 COMMENT 'JSON: Genie Space config at run start',
    triggered_by        STRING                 COMMENT 'User email who initiated the run',
    warehouse_id        STRING                 COMMENT 'SQL warehouse ID resolved at preflight; used by lever_loop / finalize / deploy as a Delta-fallback for the preflight taskValue when Repair Run drops in-memory state',
    human_corrections_json STRING              COMMENT 'JSON array of carry-forward human corrections loaded by preflight; Delta-fallback for the preflight.human_corrections taskValue',
    max_benchmark_count INT                    COMMENT 'Effective max benchmark count computed by preflight; Delta-fallback for the preflight.max_benchmark_count taskValue',
    updated_at          TIMESTAMP     NOT NULL COMMENT 'Last update timestamp'
)
USING DELTA
PARTITIONED BY (space_id)
COMMENT 'Genie Space optimization runs - one row per optimization attempt'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_STAGES_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_stages (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    task_key            STRING                 COMMENT 'Databricks Job task key (preflight, baseline_eval, lever_loop, finalize, deploy)',
    stage               STRING        NOT NULL COMMENT 'Stage name (PREFLIGHT_STARTED, LEVER_2_EVAL_DONE, etc.)',
    status              STRING        NOT NULL COMMENT 'STARTED|COMPLETE|FAILED|SKIPPED|ROLLED_BACK',
    started_at          TIMESTAMP     NOT NULL COMMENT 'When this stage began',
    completed_at        TIMESTAMP              COMMENT 'When this stage ended (null if in progress)',
    duration_seconds    DOUBLE                 COMMENT 'Wall-clock duration of this stage',
    lever               INT                    COMMENT 'Lever number (1-5) if this is a lever stage, null otherwise',
    iteration           INT                    COMMENT 'Evaluation iteration number if applicable',
    detail_json         STRING                 COMMENT 'JSON: stage-specific detail',
    error_message       STRING                 COMMENT 'Error message if status=FAILED'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Optimization stage transitions - ordered timeline of what happened'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_ITERATIONS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_iterations (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL COMMENT 'Evaluation iteration number (0 = baseline)',
    lever               INT                    COMMENT 'Which lever was applied before this eval (null for baseline)',
    eval_scope          STRING        NOT NULL COMMENT 'full|slice|p0|enrichment; legacy held_out rows may exist from older runs',
    timestamp           TIMESTAMP     NOT NULL COMMENT 'When this evaluation completed',
    overall_accuracy    DOUBLE        NOT NULL COMMENT 'Overall accuracy percentage (0-100)',
    total_questions     INT           NOT NULL COMMENT 'Number of benchmark questions evaluated',
    correct_count       INT           NOT NULL COMMENT 'Number of questions that passed all judges',
    scores_json         STRING        NOT NULL COMMENT 'JSON: per-judge scores',
    failures_json       STRING                 COMMENT 'JSON: array of failed question IDs',
    remaining_failures  STRING                 COMMENT 'JSON: array of question IDs still failing',
    arbiter_actions_json STRING                COMMENT 'JSON: array of arbiter verdicts',
    repeatability_pct   DOUBLE                 COMMENT 'Repeatability percentage (0-100) if measured',
    repeatability_json  STRING                 COMMENT 'JSON: per-question repeatability details',
    thresholds_met      BOOLEAN       NOT NULL COMMENT 'True if all quality thresholds passed',
    rows_json           STRING                 COMMENT 'JSON: per-question evaluation detail rows',
    reflection_json     STRING                 COMMENT 'JSON: adaptive loop reflection entry for this iteration',
    evaluated_count     INT                    COMMENT 'Denominator of overall_accuracy (total_questions minus runtime exclusions; see Bug #2 denominator contract)',
    excluded_count      INT                    COMMENT 'Number of rows removed from the denominator at runtime (ground-truth excluded, both empty, Genie unavailable, temporally stale, etc.)',
    quarantined_benchmarks_json STRING         COMMENT 'JSON: array of benchmarks removed by pre-evaluation quarantine ({question_id, reason_code, reason_detail, question})',
    leakage_count_by_type STRING               COMMENT 'JSON MAP<STRING,BIGINT>: Bug #4 — persisted leak count grouped by patch_type, measured by post-apply audit',
    firewall_rejection_count_by_type STRING    COMMENT 'JSON MAP<STRING,BIGINT>: Bug #4 — firewall rejections during this iteration grouped by patch_type',
    secondary_mining_blocked BIGINT            COMMENT 'Bug #4 — count of times the _resolve_lever5_llm_result secondary mining path was blocked this iteration',
    synthesis_slots_persisted BIGINT           COMMENT 'Bug #4 (Phase 3) — structurally-synthesized example_sqls persisted this iteration',
    arbiter_rejection_count BIGINT             COMMENT 'Bug #4 (Phase 3) — synthesis proposals rejected by the arbiter gate this iteration',
    cluster_fallback_to_instruction_count BIGINT COMMENT 'Bug #4 (Phase 3) — clusters that fell back to instruction-only after synthesis failed repeatedly',
    synthesis_archetype_distribution STRING    COMMENT 'JSON MAP<STRING,BIGINT>: Bug #4 (Phase 3) — count of persisted synthesized example_sqls per archetype this iteration',
    rolled_back         BOOLEAN       DEFAULT false COMMENT 'Tier 1.1: true if this iteration was rolled back by the accept/rollback gate. Readers that represent current state must filter this out (see _get_baseline_and_best_accuracy, promote_best_model, load_latest_full_iteration).',
    rolled_back_at      TIMESTAMP              COMMENT 'Tier 1.1: timestamp of rollback',
    rollback_reason     STRING                 COMMENT 'Tier 1.1: human-readable rollback reason (mirrors genie_opt_patches.rollback_reason)',
    both_correct_count  INT                    COMMENT 'Tier 1.7: count of rows with arbiter verdict == both_correct. Used to anchor best_accuracy to both_correct_rate when rc=yes overrides inflate overall_accuracy.',
    both_correct_rate   DOUBLE                 COMMENT 'Tier 1.7: both_correct_count / evaluated_count * 100. Stricter than overall_accuracy (which counts arbiter override rows as correct). Lever loop anchors acceptance to this to avoid ghost-ceiling rejections.',
    config_json         STRING                 COMMENT 'GSO v2 Phase 4 (D3): JSON of the FULL effective Genie Space config in force for THIS iteration (baseline iter 0, patch/eval iterations 1..N). Whitelisted Genie-domain projection (optimizer-internal _* keys dropped). Delta is the sole config/version store; CDF gives versioned history.',
    is_champion         BOOLEAN       DEFAULT false COMMENT 'GSO v2 Phase 4 (D3): true on the single champion iteration row (the best iteration as chosen by the existing Delta-driven selection in promote_best_model). Marked in Delta only — NO UC model registration.',
    num_needs_review    INT                    COMMENT 'GSO v2 Phase 6: count of per-question rows whose official assessment is NEEDS_REVIEW (neither GOOD nor BAD). Surfaced by the Workbench /iterations endpoint so the UI can distinguish review-pending from failing questions. Sourced from build_eval_output_from_official; NULL on legacy/repeatability-only rows.',
    eval_run_id         STRING                 COMMENT 'GSO v2 Phase 6: native Genie benchmark eval-run id for this iteration (from the official EvalRunner). Surfaced so the UI can reference the underlying eval run. NULL on the legacy in-process path.',
    eval_run_status     STRING                 COMMENT 'GSO v2 Phase 6: native eval-run terminal status (e.g. DONE / EVALUATION_FAILED / CANCELLED) for this iteration. NULL on the legacy in-process path.',
    attempt_no          INT                    COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): monotonic display counter for the optimize loop — 0=baseline, 1..N=LLM patch/eval attempts.',
    attempt_mode        STRING                 COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): baseline or llm_patch.',
    best_accuracy       DOUBLE                 COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): best full-benchmark accuracy seen so far at the end of this attempt (the champion staircase value).',
    best_config_version_id STRING              COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): serialized config snapshot reference for the current champion.',
    current_hypothesis  STRING                 COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): JSON of the active patch hypothesis tested in this attempt.',
    do_not_repeat       STRING                 COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): JSON ARRAY of rejected lever families / strategies the controller will not retry.',
    terminal_reason     STRING                 COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): TARGET_REACHED | MAX_ATTEMPTS | NO_NEW_HYPOTHESIS | EVAL_INVALID | EVAL_BUDGET_EXHAUSTED. Set on the champion row only.',
    decision            STRING                 COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): per-attempt aggregate decision — accept | reject | continue.',
    decision_reason     STRING                 COMMENT 'GSO v2 Phase 7 (loop-state, arch §7.4): human-readable reason for the decision (e.g. rolled_back (Δacc<0), no_enrichment_candidates).',
    surgical_attempts_used INT                 COMMENT 'GSO v2 Phase 8 (loop-state, arch §7.4): patch/eval attempt budget consumed so far.',
    next_hypothesis     STRING                 COMMENT 'GSO v2 Phase 8 (loop-state, arch §7.4): JSON of the next patch idea the controller chose from the residual failures.',
    target_accuracy     DOUBLE                 COMMENT 'GSO v2 Phase 8 (loop-state, arch §7.4): stop-early target accuracy in force for this run (0-100 scale; default 90.0).',
    max_attempts        INT                    COMMENT 'GSO v2 Phase 8 (loop-state, arch §7.4): patch/eval attempt budget in force for this run (default 3).'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Evaluation iteration results - scores and failures per eval pass'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true',
    'delta.feature.allowColumnDefaults' = 'supported'
)"""

_GENIE_OPT_PATCHES_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_patches (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL COMMENT 'Iteration when this patch was applied',
    lever               INT           NOT NULL COMMENT 'Lever number (1-5)',
    patch_index         INT           NOT NULL COMMENT 'Index within the patch set',
    patch_type          STRING        NOT NULL COMMENT 'Patch type from PATCH_TYPES',
    scope               STRING        NOT NULL COMMENT 'genie_config or uc_artifact or both',
    risk_level          STRING        NOT NULL COMMENT 'low|medium|high',
    target_object       STRING                 COMMENT 'Object being modified (table name, column name, etc.)',
    patch_json          STRING        NOT NULL COMMENT 'JSON: full patch definition',
    command_json        STRING                 COMMENT 'JSON: rendered action command',
    rollback_json       STRING                 COMMENT 'JSON: rollback command',
    applied_at          TIMESTAMP     NOT NULL COMMENT 'When the patch was applied',
    rolled_back         BOOLEAN                COMMENT 'True if this patch was subsequently rolled back',
    rolled_back_at      TIMESTAMP              COMMENT 'When the rollback occurred',
    rollback_reason     STRING                 COMMENT 'Why the patch was rolled back',
    proposal_id         STRING                 COMMENT 'FK to the proposal that generated this patch',
    cluster_id          STRING                 COMMENT 'Failure cluster that motivated this patch',
    provenance_json     STRING                 COMMENT 'JSON: full provenance chain from judge verdicts to this patch'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Patch audit trail - every metadata change applied to Genie Space'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_DATA_ACCESS_GRANTS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_data_access_grants (
    grant_id            STRING        NOT NULL COMMENT 'UUID for this grant record',
    target_catalog      STRING        NOT NULL COMMENT 'Catalog the SP was granted access to',
    target_schema       STRING        NOT NULL COMMENT 'Schema the SP was granted access to',
    granted_by          STRING        NOT NULL COMMENT 'User who performed the grant',
    granted_at          TIMESTAMP     NOT NULL COMMENT 'When the grant was applied',
    revoked_at          TIMESTAMP              COMMENT 'When the grant was revoked (null if active)',
    status              STRING        NOT NULL COMMENT 'active|revoked',
    grant_type          STRING        NOT NULL COMMENT 'read|write — read grants SELECT/EXECUTE, write adds MODIFY'
)
USING DELTA
COMMENT 'Tracks UC privileges granted to the app SP for accessing Genie space assets'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_PROVENANCE_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_provenance (
    run_id              STRING        NOT NULL  COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL  COMMENT 'Lever loop iteration',
    lever               INT           NOT NULL  COMMENT 'Lever number (1-5)',
    question_id         STRING        NOT NULL  COMMENT 'Benchmark question ID',
    signal_type         STRING        NOT NULL  COMMENT 'hard or soft',
    arbiter_verdict     STRING                  COMMENT 'Arbiter verdict for this question',
    judge               STRING        NOT NULL  COMMENT 'Judge that failed',
    judge_verdict       STRING        NOT NULL  COMMENT 'Judge verdict (PASS/FAIL)',
    asi_failure_type_raw STRING                 COMMENT 'Raw failure_type from ASI metadata',
    resolved_root_cause STRING        NOT NULL  COMMENT 'Final root cause after resolution chain',
    resolution_method   STRING        NOT NULL  COMMENT 'asi_metadata or rationale_pattern or sql_diff',
    blame_set           STRING                  COMMENT 'JSON array of blamed objects',
    counterfactual_fix  STRING                  COMMENT 'Suggested fix from judge',
    wrong_clause        STRING                  COMMENT 'SQL clause identified as wrong',
    rationale_snippet   STRING                  COMMENT 'First 500 chars of judge rationale',
    expected_sql        STRING                  COMMENT 'Expected SQL (first 2000 chars)',
    generated_sql       STRING                  COMMENT 'Generated SQL (first 2000 chars)',
    cluster_id          STRING        NOT NULL  COMMENT 'Cluster this question was grouped into',
    proposal_id         STRING                  COMMENT 'Proposal generated from this cluster',
    patch_type          STRING                  COMMENT 'Type of patch applied',
    gate_type           STRING                  COMMENT 'slice or p0 or full',
    gate_result         STRING                  COMMENT 'pass or fail or rollback',
    gate_regression     STRING                  COMMENT 'JSON regression details if gate failed',
    logged_at           TIMESTAMP     NOT NULL  COMMENT 'When this row was written'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'End-to-end provenance: links every patch to originating judge verdicts and gate outcomes'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_FINALIZE_ATTESTATION_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_finalize_attestation_matrix (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    qid                 STRING        NOT NULL COMMENT 'Benchmark question_id',
    iteration_idx       STRING        NOT NULL COMMENT 'Canonical marker: "baseline" | "final" | integer iteration index',
    passed              BOOLEAN                COMMENT 'True if the question passed in this sweep (NULL = quarantined/excluded)',
    is_heldout          BOOLEAN       NOT NULL COMMENT 'Legacy compatibility marker; V2 uses the full benchmark corpus',
    logged_at           TIMESTAMP     NOT NULL COMMENT 'When this row was written'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Bug #4 Phase 4 — per-qid pass/fail matrix from baseline + finalize full-corpus sweeps. Drives the user-visible final_accuracy - baseline_accuracy summary.'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_SUGGESTIONS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_suggestions (
    suggestion_id       STRING        NOT NULL COMMENT 'UUID for this suggestion',
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    space_id            STRING        NOT NULL COMMENT 'Genie Space ID',
    iteration           INT                    COMMENT 'Lever-loop iteration that produced this suggestion',
    lever               INT                    COMMENT 'Lever number that produced this suggestion',
    type                STRING        NOT NULL COMMENT 'METRIC_VIEW | FUNCTION',
    title               STRING        NOT NULL COMMENT 'Short human-readable title',
    rationale           STRING                 COMMENT 'Why the strategist proposed this',
    definition          STRING                 COMMENT 'SQL or pseudocode definition',
    affected_questions  STRING                 COMMENT 'JSON array of question IDs that would benefit',
    estimated_impact    STRING                 COMMENT 'Estimated accuracy improvement description',
    status              STRING        NOT NULL COMMENT 'PROPOSED | ACCEPTED | REJECTED | IMPLEMENTED',
    reviewed_by         STRING                 COMMENT 'User who reviewed the suggestion',
    reviewed_at         TIMESTAMP              COMMENT 'When the suggestion was reviewed',
    created_at          TIMESTAMP     NOT NULL COMMENT 'When the suggestion was created',
    updated_at          TIMESTAMP     NOT NULL COMMENT 'Last update timestamp'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Strategist improvement suggestions — proposed metric views and functions for human review'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

# Task 3: lever-loop decision audit. ``stage_letter`` follows the
# Pipeline Hand-off Contract (A..O) so a single query joins every
# decision back to its eval pass. ``proposal_to_patch_map_json`` is
# non-null on apply / acceptance rows; the attribution invariant lives
# in ``test_decision_audit.py``.
_GENIE_EVAL_LEVER_LOOP_DECISIONS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_eval_lever_loop_decisions (
    run_id                       STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration                    INT           NOT NULL COMMENT 'Iteration index',
    ag_id                        STRING                 COMMENT 'Action group id; NULL for pre-AG rows',
    decision_order               INT           NOT NULL COMMENT 'Monotonic order within an AG; ties broken by created_at',
    stage_letter                 STRING                 COMMENT 'Pipeline Hand-off Contract letter (A..O)',
    gate_name                    STRING        NOT NULL COMMENT 'Logical gate name: full_eval_acceptance, post_arbiter_guardrail, asi_extraction, proposal_grounding, ...',
    decision                     STRING        NOT NULL COMMENT 'accepted | rolled_back | dropped | pass | fail | ok | degraded',
    reason_code                  STRING                 COMMENT 'Stable code for the decision (e.g. post_arbiter_guardrail, primary_not_improved_in_every_run)',
    reason_detail                STRING                 COMMENT 'Free-text detail; size-bounded to 2000 chars',
    affected_qids_json           STRING                 COMMENT 'JSON array of question ids the decision affected',
    source_cluster_ids_json      STRING                 COMMENT 'JSON array of cluster ids producing the inputs to this decision',
    proposal_ids_json            STRING                 COMMENT 'JSON array of proposal ids the decision evaluated',
    proposal_to_patch_map_json   STRING                 COMMENT 'JSON object {proposal_id: applied_patch_id}; non-null on apply / acceptance rows',
    metrics_json                 STRING                 COMMENT 'JSON object with typed metrics (deltas, counts, scores)',
    created_at                   TIMESTAMP     NOT NULL COMMENT 'When the decision was emitted'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Lever-loop decision audit trail — every gate decision lands here for queryable attribution'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

# Task 8: human-required escalation queue. Persisted record of the
# cluster signatures the optimizer is giving up on within a run. The
# associated qids are excluded from future strategist input until a
# reviewer either fixes the underlying GT or instruction gap. Each
# row carries the typed evidence (recent rollback reasons,
# attempt_count, root_cause) needed for the reviewer to act on the
# case without scrolling stdout.
_GENIE_EVAL_HUMAN_REQUIRED_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_eval_human_required (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    cluster_signature   STRING        NOT NULL COMMENT 'sha1-derived cluster identity (Task 2.1)',
    question_id         STRING                 COMMENT 'Affected qid (one row per qid)',
    root_cause          STRING                 COMMENT 'Dominant root cause from the cluster',
    attempt_count       INT                    COMMENT 'Distinct content-regression rollbacks observed',
    last_iteration      INT                    COMMENT 'Iteration of the most recent rollback',
    reason_code         STRING                 COMMENT 'persistent_content_rollback | stuck_convergence',
    evidence_json       STRING                 COMMENT 'Compact JSON evidence: rollback reasons, levers tried, score deltas',
    created_at          TIMESTAMP     NOT NULL COMMENT 'When the escalation was filed'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Cluster signatures the optimizer escalated to human review within a run (Task 8)'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

# Task 9: proactive feature-mining persistence. Two tables —
# ``genie_eval_proactive_corpus_profile`` records the aggregate
# profile per run (what frequencies the miner observed across the
# passing corpus); ``genie_eval_proactive_patches`` records the
# emitted enrichment patches with their ``source_signal`` (what
# observation drove the proposal) and ``frequency`` (how strong the
# evidence was). Together they let a reviewer audit the proactive
# pipeline without replaying the run.
_GENIE_EVAL_PROACTIVE_CORPUS_PROFILE_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_eval_proactive_corpus_profile (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL COMMENT 'Iteration index where the profile was computed (typically 0)',
    table_id            STRING                 COMMENT 'Asset id the profile is scoped to',
    profile_blob        STRING                 COMMENT 'JSON-serialized CorpusProfile counters',
    eligible_row_count  INT                    COMMENT 'Passing rows that contributed to the profile',
    created_at          TIMESTAMP     NOT NULL COMMENT 'When the profile was persisted'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Aggregate corpus feature profiles from Task 9 proactive mining'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_EVAL_PROACTIVE_PATCHES_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_eval_proactive_patches (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL COMMENT 'Iteration index where the patch was generated',
    patch_id            STRING        NOT NULL COMMENT 'Stable id within (run_id, iteration)',
    patch_type          STRING                 COMMENT 'update_column_description | add_join_spec | add_sql_snippet_expression | ...',
    target              STRING                 COMMENT 'Table.column or join target',
    table_id            STRING                 COMMENT 'Asset id the patch enriches',
    source_signal       STRING                 COMMENT 'What observation drove the proposal (e.g. co_occurs_with:dim, frequent_tvf)',
    frequency           INT                    COMMENT 'Observed frequency of the source signal',
    dedup_route         STRING                 COMMENT 'metric_view_measure_enrich when the candidate was rewritten by the dedup contract',
    dedup_dropped_reason STRING                COMMENT 'Reason code when the dedup contract dropped the candidate',
    applied             BOOLEAN                COMMENT 'True when the patch was applied to the space',
    created_at          TIMESTAMP     NOT NULL COMMENT 'When the patch was generated'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Enrichment patches emitted by Task 9 proactive mining (one row per candidate)'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

# Task 1: ground-truth correction queue. ``status`` is the four-state
# review machine documented in ``ground_truth_corrections``:
#   pending_review        — initial; reviewer has not looked.
#   accepted_corpus_fix   — GT was updated; qid eligible for proactive
#                           mining (Task 9 reads this status).
#   rejected_keep_gt      — reviewer disagreed; treat as confirmed Genie
#                           failure on next iteration.
#   superseded            — replaced by a later iteration's row.
_GENIE_EVAL_GT_CORRECTION_CANDIDATES_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_eval_gt_correction_candidates (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL COMMENT 'Iteration that produced this candidate',
    question_id         STRING        NOT NULL COMMENT 'Benchmark question id',
    question            STRING                 COMMENT 'Question text (frozen at capture time)',
    expected_sql        STRING                 COMMENT 'Ground-truth SQL believed wrong by the arbiter',
    genie_sql           STRING                 COMMENT 'Genie-produced SQL the arbiter ruled correct',
    arbiter_verdict     STRING                 COMMENT 'Arbiter verdict; expected genie_correct',
    arbiter_rationale   STRING                 COMMENT 'Arbiter explanation for the genie_correct verdict',
    status              STRING        NOT NULL COMMENT 'pending_review | accepted_corpus_fix | rejected_keep_gt | superseded',
    created_at          TIMESTAMP     NOT NULL COMMENT 'When the candidate was queued'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Corpus-review queue for benchmark rows where the arbiter ruled Genie correct against a defective GT'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

# GSO v2 (§3.5): benchmark-mutation provenance ledger. One row per GSO
# mutation to the user's LIVE Genie Space benchmark set — added at the
# preflight push, removed at the EXPLAIN-invalid / validation prune,
# changed at auto-correction. ``before`` / ``after`` carry the question
# text + SQL so the Workbench UI can render the added/removed/changed diff
# (the backend endpoint + view are Phase 6 — out of scope for the engine
# write path defined here). The preflight ``config_snapshot`` on
# genie_opt_runs remains the discard revert anchor; this ledger is a
# transparency record, not a rollback mechanism.
_GENIE_OPT_BENCHMARK_MUTATIONS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_benchmark_mutations (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    question_id         STRING        NOT NULL COMMENT 'Benchmark question id the mutation applies to',
    op                  STRING        NOT NULL COMMENT 'added | removed | changed | prune_recommended (advisory, non-mutating)',
    before              STRING                 COMMENT 'JSON {question, sql} prior state (NULL for added)',
    after               STRING                 COMMENT 'JSON {question, sql} new state (NULL for removed / prune_recommended)',
    reason              STRING                 COMMENT 'Why GSO made this mutation (preflight_push | explain_invalid | over_window_recommendation | ...)',
    logged_at           TIMESTAMP     NOT NULL COMMENT 'When this mutation was recorded'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'GSO v2 provenance ledger — every benchmark question GSO added/removed/changed in the live Genie Space'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

# GSO v2 orchestration (Phase 7, arch §7.1): generic Delta handoff table for
# the stage-level fat JSON blobs that don't fit a per-attempt scored row.
# Scoped to 3 artifact_kind values — run_manifest, benchmark_qc,
# publish_record. Per-attempt truth (scores, loop-state,
# patches, decisions) lives in genie_opt_iterations / genie_opt_patches /
# genie_eval_lever_loop_decisions, NOT here (see arch §7 reconciliation).
_GENIE_OPT_ARTIFACTS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_artifacts (
    artifact_id         STRING        NOT NULL COMMENT 'UUID for this artifact row',
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    stage_name          STRING                 COMMENT 'Notebook or stage that wrote the artifact (intake_and_snapshot, benchmark_qc_and_repair, ...)',
    iteration           INT                    COMMENT 'Iteration number, when applicable (NULL for run-level artifacts)',
    artifact_kind       STRING        NOT NULL COMMENT 'run_manifest | benchmark_qc | publish_record',
    artifact_json       STRING                 COMMENT 'JSON payload for the artifact (enough to reconstruct the pass without notebook-local state)',
    content_hash        STRING                 COMMENT 'Hash of artifact_json for dedupe / idempotency / replay safety',
    parent_artifact_id  STRING                 COMMENT 'Lineage pointer to the artifact this one derives from',
    source_notebook     STRING                 COMMENT 'Notebook name that produced the row',
    created_at          TIMESTAMP     NOT NULL COMMENT 'Write timestamp'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'GSO v2 (arch §7.1) generic Delta handoff table for stage-level JSON blobs (run_manifest, benchmark_qc, publish_record)'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

# ── Combined DDL dict ────────────────────────────────────────────────────
#
# GSO v2 orchestration (Phase 7, arch §7): the 8 retired 6-notebook tables
# (ASI judge, MLflow human-review, enrichment sidecars, finalize attestation,
# suggestions, subset-gate regressions, GT-correction candidates) plus
# genie_opt_data_access_grants are NO LONGER created — they were removed from
# this dict so fresh installs never get them, and existing installs are
# rename-retired to ``*_deprecated`` by ``state.migrate_retire_dropped_tables``
# (see ``RETIRED_TABLES`` below). genie_opt_artifacts is added; the loop-state
# columns are folded into genie_opt_iterations (see ADDITIVE_COLUMN_MIGRATIONS).
_ALL_DDL: dict[str, str] = {
    TABLE_RUNS: _GENIE_OPT_RUNS_DDL,
    TABLE_STAGES: _GENIE_OPT_STAGES_DDL,
    TABLE_ITERATIONS: _GENIE_OPT_ITERATIONS_DDL,
    TABLE_PATCHES: _GENIE_OPT_PATCHES_DDL,
    TABLE_PROVENANCE: _GENIE_OPT_PROVENANCE_DDL,
    TABLE_LEVER_LOOP_DECISIONS: _GENIE_EVAL_LEVER_LOOP_DECISIONS_DDL,
    TABLE_BENCHMARK_MUTATIONS: _GENIE_OPT_BENCHMARK_MUTATIONS_DDL,
    TABLE_ARTIFACTS: _GENIE_OPT_ARTIFACTS_DDL,
}

# GSO v2 orchestration (Phase 7, arch §7): tables tied to retired 6-notebook
# stages, no longer created (removed from _ALL_DDL above). The one-shot
# migration in ``state.migrate_retire_dropped_tables`` DROPs these on fresh
# installs (they were never created) or RENAMEs them to ``<name>_deprecated``
# on existing installs (data preserved, never hard-dropped). Idempotent.
RETIRED_TABLES: tuple[str, ...] = (
    TABLE_ASI,                       # ASI judge feedback — judges retired (Phase 3 / D2)
    TABLE_HUMAN_REQUIRED,            # MLflow human-review escalation — retired (Phase 5 / D7)
    TABLE_PROACTIVE_CORPUS_PROFILE,  # old enrichment sidecar — folded into 03 coverage pass
    TABLE_PROACTIVE_PATCHES,         # old enrichment sidecar — folded; use genie_opt_patches
    TABLE_FINALIZE_ATTESTATION,      # old finalize attestation — superseded by publish_record artifact
    TABLE_SUGGESTIONS,               # old suggestions output — superseded by artifacts
    TABLE_QUESTION_REGRESSIONS,      # subset-gate regression tracking — subset-first 3-gate retired for the loop
    TABLE_GT_CORRECTION_CANDIDATES,  # bespoke GT-correction — folded into the benchmark_qc artifact
    TABLE_DATA_ACCESS_GRANTS,        # no runtime writer (markdown-only refs) — dropped
)


ADDITIVE_COLUMN_MIGRATIONS: tuple[tuple[str, str, str], ...] = (
    (TABLE_RUNS, "job_id", "STRING COMMENT 'Databricks Job definition ID'"),
    (TABLE_PATCHES, "provenance_json", "STRING COMMENT 'JSON: full provenance chain from judge verdicts to this patch'"),
    (TABLE_RUNS, "llm_model", "STRING COMMENT 'Databricks Model Serving endpoint selected for this optimization run'"),
    (TABLE_ITERATIONS, "reflection_json", "STRING COMMENT 'JSON: adaptive loop reflection entry for this iteration'"),
    (TABLE_DATA_ACCESS_GRANTS, "grant_type", "STRING DEFAULT 'read' COMMENT 'read|write - read grants SELECT/EXECUTE, write adds MODIFY'"),
    (TABLE_ITERATIONS, "evaluated_count", "INT COMMENT 'Denominator of overall_accuracy (total_questions minus runtime exclusions; see Bug #2 denominator contract)'"),
    (TABLE_ITERATIONS, "excluded_count", "INT COMMENT 'Number of rows removed from the denominator at runtime (ground-truth excluded, both empty, Genie unavailable, temporally stale, etc.)'"),
    (TABLE_ITERATIONS, "quarantined_benchmarks_json", "STRING COMMENT 'JSON: array of benchmarks removed by pre-evaluation quarantine ({question_id, reason_code, reason_detail, question})'"),
    (TABLE_ITERATIONS, "leakage_count_by_type", "STRING COMMENT 'JSON MAP<STRING,BIGINT>: Bug #4 - persisted leak count grouped by patch_type, measured by post-apply audit'"),
    (TABLE_ITERATIONS, "firewall_rejection_count_by_type", "STRING COMMENT 'JSON MAP<STRING,BIGINT>: Bug #4 - firewall rejections during this iteration grouped by patch_type'"),
    (TABLE_ITERATIONS, "secondary_mining_blocked", "BIGINT COMMENT 'Bug #4 - count of times the _resolve_lever5_llm_result secondary mining path was blocked this iteration'"),
    (TABLE_ITERATIONS, "synthesis_slots_persisted", "BIGINT COMMENT 'Bug #4 (Phase 3) - structurally-synthesized example_sqls persisted this iteration'"),
    (TABLE_ITERATIONS, "arbiter_rejection_count", "BIGINT COMMENT 'Bug #4 (Phase 3) - synthesis proposals rejected by the arbiter gate'"),
    (TABLE_ITERATIONS, "cluster_fallback_to_instruction_count", "BIGINT COMMENT 'Bug #4 (Phase 3) - clusters that fell back to instruction-only after synthesis failed repeatedly'"),
    (TABLE_ITERATIONS, "synthesis_archetype_distribution", "STRING COMMENT 'JSON MAP<STRING,BIGINT>: Bug #4 (Phase 3) - count of persisted synthesized example_sqls per archetype this iteration'"),
    (TABLE_ITERATIONS, "rolled_back", "BOOLEAN DEFAULT false COMMENT 'Tier 1.1: true if this iteration was rolled back by the accept/rollback gate. Readers that represent current state must filter this out (see _get_baseline_and_best_accuracy, promote_best_model, load_latest_full_iteration).'"),
    (TABLE_ITERATIONS, "rolled_back_at", "TIMESTAMP COMMENT 'Tier 1.1: timestamp of rollback'"),
    (TABLE_ITERATIONS, "rollback_reason", "STRING COMMENT 'Tier 1.1: human-readable rollback reason (mirrors genie_opt_patches.rollback_reason)'"),
    (TABLE_ITERATIONS, "both_correct_count", "INT COMMENT 'Tier 1.7: count of rows with arbiter verdict == both_correct. Used to anchor best_accuracy to both_correct_rate when rc=yes overrides inflate overall_accuracy.'"),
    (TABLE_ITERATIONS, "both_correct_rate", "DOUBLE COMMENT 'Tier 1.7: both_correct_count / evaluated_count * 100. Stricter than overall_accuracy (which counts arbiter override rows as correct). Lever loop anchors acceptance to this to avoid ghost-ceiling rejections.'"),
    (TABLE_PATCHES, "applied_patch_type", "STRING COMMENT 'T2.13: actual patch_type that was applied after any applier-side transformations (e.g. update_instruction_section emitted by the rewrite_instruction downgrade splitter). May differ from patch_type (the proposal type).'"),
    (TABLE_PATCHES, "applied_patch_detail", "STRING COMMENT 'T2.13: human-readable detail describing the applied transformation (e.g. section_name for update_instruction_section, or a note when a rewrite_instruction was split into children).'"),
    (TABLE_RUNS, "warehouse_id", "STRING COMMENT 'SQL warehouse ID resolved at preflight; Delta-fallback for the preflight.warehouse_id taskValue'"),
    (TABLE_RUNS, "human_corrections_json", "STRING COMMENT 'JSON array of carry-forward human corrections; Delta-fallback for the preflight.human_corrections taskValue'"),
    (TABLE_RUNS, "max_benchmark_count", "INT COMMENT 'Effective max benchmark count; Delta-fallback for the preflight.max_benchmark_count taskValue'"),
    (TABLE_ITERATIONS, "config_json", "STRING COMMENT 'GSO v2 Phase 4 (D3): JSON of the FULL effective Genie Space config in force for this iteration. Whitelisted Genie-domain projection (optimizer-internal _* keys dropped). Delta is the sole config/version store; CDF gives versioned history.'"),
    (TABLE_ITERATIONS, "is_champion", "BOOLEAN DEFAULT false COMMENT 'GSO v2 Phase 4 (D3): true on the single champion iteration row (best iteration per the existing Delta-driven selection in promote_best_model). Marked in Delta only — NO UC model registration.'"),
    (TABLE_ITERATIONS, "num_needs_review", "INT COMMENT 'GSO v2 Phase 6: count of per-question rows whose official assessment is NEEDS_REVIEW. Surfaced by the Workbench /iterations endpoint. NULL on legacy/repeatability-only rows.'"),
    (TABLE_ITERATIONS, "eval_run_id", "STRING COMMENT 'GSO v2 Phase 6: native Genie benchmark eval-run id for this iteration (from the official EvalRunner). NULL on the legacy in-process path.'"),
    (TABLE_ITERATIONS, "eval_run_status", "STRING COMMENT 'GSO v2 Phase 6: native eval-run terminal status (DONE / EVALUATION_FAILED / CANCELLED). NULL on the legacy in-process path.'"),
    # GSO v2 Phase 7 (loop-state, arch §7.4): genie_opt_iterations is the
    # single per-attempt truth — extend it with the controller loop-state
    # columns alongside the Phase-4 config_json/is_champion. The unified
    # optimize loop writes these for baseline + each LLM patch/eval attempt.
    (TABLE_ITERATIONS, "attempt_no", "INT COMMENT 'GSO v2 Phase 7 (loop-state): monotonic display counter — 0=baseline, 1..N=LLM patch/eval attempts.'"),
    (TABLE_ITERATIONS, "attempt_mode", "STRING COMMENT 'GSO v2 Phase 7 (loop-state): baseline or llm_patch.'"),
    (TABLE_ITERATIONS, "best_accuracy", "DOUBLE COMMENT 'GSO v2 Phase 7 (loop-state): best full-benchmark accuracy so far (champion staircase value).'"),
    (TABLE_ITERATIONS, "best_config_version_id", "STRING COMMENT 'GSO v2 Phase 7 (loop-state): serialized config snapshot reference for the current champion.'"),
    (TABLE_ITERATIONS, "current_hypothesis", "STRING COMMENT 'GSO v2 Phase 7 (loop-state): JSON of the active patch hypothesis tested in this attempt.'"),
    (TABLE_ITERATIONS, "do_not_repeat", "STRING COMMENT 'GSO v2 Phase 7 (loop-state): JSON ARRAY of rejected lever families / strategies.'"),
    (TABLE_ITERATIONS, "terminal_reason", "STRING COMMENT 'GSO v2 Phase 7 (loop-state): TARGET_REACHED | MAX_ATTEMPTS | NO_NEW_HYPOTHESIS | EVAL_INVALID | EVAL_BUDGET_EXHAUSTED.'"),
    (TABLE_ITERATIONS, "decision", "STRING COMMENT 'GSO v2 Phase 7 (loop-state): per-attempt aggregate decision — accept | reject | continue.'"),
    (TABLE_ITERATIONS, "decision_reason", "STRING COMMENT 'GSO v2 Phase 7 (loop-state): human-readable reason for the decision.'"),
    # GSO v2 Phase 8 (loop-state, arch §7.4): the unified optimize loop adds
    # the consumed-attempt counter, next-hypothesis pointer, and the two run-level
    # stop knobs (target_accuracy / max_attempts) as per-attempt columns so the
    # Attempt Ladder/Ledger and resume read one self-describing row.
    (TABLE_ITERATIONS, "surgical_attempts_used", "INT COMMENT 'GSO v2 Phase 8 (loop-state): patch/eval attempt budget consumed so far.'"),
    (TABLE_ITERATIONS, "next_hypothesis", "STRING COMMENT 'GSO v2 Phase 8 (loop-state): JSON of the next patch idea chosen by the controller from residual failures.'"),
    (TABLE_ITERATIONS, "target_accuracy", "DOUBLE COMMENT 'GSO v2 Phase 8 (loop-state): stop-early target accuracy in force (0-100 scale; default 90.0).'"),
    (TABLE_ITERATIONS, "max_attempts", "INT COMMENT 'GSO v2 Phase 8 (loop-state): patch/eval attempt budget in force (default 3).'"),
)
