"""DDL constants for GSO optimization Delta tables.

Extracted into a standalone module so that deploy scripts (e.g.
``scripts/setup_workbench.py``) can import ``_ALL_DDL`` without
pulling in pandas or other heavy runtime dependencies.
"""

from genie_space_optimizer.common.config import (
    TABLE_ASI,
    TABLE_ITERATIONS,
    TABLE_PATCHES,
    TABLE_PROVENANCE,
    TABLE_RUNS,
    TABLE_STAGES,
    TABLE_SUGGESTIONS,
)

# ── Table Names (not in common/config.py) ─────────────────────────────

TABLE_DATA_ACCESS_GRANTS = "genie_opt_data_access_grants"

# ── DDL Constants ────────────────────────────────────────────────────────

_GENIE_OPT_RUNS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_runs (
    run_id              STRING        NOT NULL COMMENT 'UUID for this optimization run',
    space_id            STRING        NOT NULL COMMENT 'Genie Space ID being optimized',
    domain              STRING        NOT NULL COMMENT 'Domain name (e.g. revenue_property)',
    catalog             STRING        NOT NULL COMMENT 'Unity Catalog name',
    uc_schema           STRING        NOT NULL COMMENT 'UC schema (catalog.schema format)',
    status              STRING        NOT NULL COMMENT 'QUEUED|IN_PROGRESS|CONVERGED|STALLED|MAX_ITERATIONS|FAILED|CANCELLED',
    started_at          TIMESTAMP     NOT NULL COMMENT 'When the run was created',
    completed_at        TIMESTAMP              COMMENT 'When the run reached a terminal state',
    job_run_id          STRING                 COMMENT 'Databricks Job run ID',
    job_id              STRING                 COMMENT 'Databricks Job definition ID',
    max_iterations      INT           NOT NULL COMMENT 'Maximum lever iterations allowed',
    levers              STRING        NOT NULL COMMENT 'JSON array of lever numbers to try, e.g. [1,2,3,4,5]',
    apply_mode          STRING        NOT NULL COMMENT 'Where patches are applied: genie_config|uc_artifact|both',
    deploy_target       STRING                 COMMENT 'DABs target for post-optimization deploy (null = no deploy)',
    benchmarks_generated BOOLEAN                COMMENT 'True if benchmarks were auto-generated by LLM during this run',
    best_iteration      INT                    COMMENT 'Iteration number with highest accuracy',
    best_accuracy       DOUBLE                 COMMENT 'Best overall accuracy achieved (0-100)',
    best_repeatability  DOUBLE                 COMMENT 'Best repeatability percentage (0-100)',
    best_model_id       STRING                 COMMENT 'MLflow LoggedModel ID for the best iteration',
    convergence_reason  STRING                 COMMENT 'Why the run stopped (threshold_met|plateau|max_iterations|error)',
    experiment_name     STRING                 COMMENT 'MLflow experiment path',
    experiment_id       STRING                 COMMENT 'MLflow experiment ID',
    config_snapshot     STRING                 COMMENT 'JSON: Genie Space config at run start',
    triggered_by        STRING                 COMMENT 'User email who initiated the run',
    labeling_session_name STRING               COMMENT 'MLflow labeling session name for human review',
    labeling_session_run_id STRING             COMMENT 'MLflow run ID associated with the labeling session',
    labeling_session_url STRING                COMMENT 'URL to the MLflow Review App labeling session',
    updated_at          TIMESTAMP     NOT NULL COMMENT 'Last update timestamp'
)
USING DELTA
PARTITIONED BY (space_id)
COMMENT 'Genie Space optimization runs - one row per optimization attempt'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_STAGES_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_stages (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    task_key            STRING                 COMMENT 'Databricks Job task key (preflight, baseline_eval, lever_loop, finalize, deploy)',
    stage               STRING        NOT NULL COMMENT 'Stage name (PREFLIGHT_STARTED, LEVER_2_EVAL_DONE, etc.)',
    status              STRING        NOT NULL COMMENT 'STARTED|COMPLETE|FAILED|SKIPPED|ROLLED_BACK',
    started_at          TIMESTAMP     NOT NULL COMMENT 'When this stage began',
    completed_at        TIMESTAMP              COMMENT 'When this stage ended (null if in progress)',
    duration_seconds    DOUBLE                 COMMENT 'Wall-clock duration of this stage',
    lever               INT                    COMMENT 'Lever number (1-5) if this is a lever stage, null otherwise',
    iteration           INT                    COMMENT 'Evaluation iteration number if applicable',
    detail_json         STRING                 COMMENT 'JSON: stage-specific detail',
    error_message       STRING                 COMMENT 'Error message if status=FAILED'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Optimization stage transitions - ordered timeline of what happened'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_ITERATIONS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_iterations (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL COMMENT 'Evaluation iteration number (0 = baseline)',
    lever               INT                    COMMENT 'Which lever was applied before this eval (null for baseline)',
    eval_scope          STRING        NOT NULL COMMENT 'full|slice|p0|held_out',
    timestamp           TIMESTAMP     NOT NULL COMMENT 'When this evaluation completed',
    mlflow_run_id       STRING                 COMMENT 'MLflow run ID for this evaluation',
    model_id            STRING                 COMMENT 'LoggedModel ID used for this evaluation',
    overall_accuracy    DOUBLE        NOT NULL COMMENT 'Overall accuracy percentage (0-100)',
    total_questions     INT           NOT NULL COMMENT 'Number of benchmark questions evaluated',
    correct_count       INT           NOT NULL COMMENT 'Number of questions that passed all judges',
    scores_json         STRING        NOT NULL COMMENT 'JSON: per-judge scores',
    failures_json       STRING                 COMMENT 'JSON: array of failed question IDs',
    remaining_failures  STRING                 COMMENT 'JSON: array of question IDs still failing',
    arbiter_actions_json STRING                COMMENT 'JSON: array of arbiter verdicts',
    repeatability_pct   DOUBLE                 COMMENT 'Repeatability percentage (0-100) if measured',
    repeatability_json  STRING                 COMMENT 'JSON: per-question repeatability details',
    thresholds_met      BOOLEAN       NOT NULL COMMENT 'True if all quality thresholds passed',
    rows_json           STRING                 COMMENT 'JSON: per-question evaluation detail rows',
    reflection_json     STRING                 COMMENT 'JSON: adaptive loop reflection entry for this iteration',
    evaluated_count     INT                    COMMENT 'Denominator of overall_accuracy (total_questions minus runtime exclusions; see Bug #2 denominator contract)',
    excluded_count      INT                    COMMENT 'Number of rows removed from the denominator at runtime (ground-truth excluded, both empty, Genie unavailable, temporally stale, etc.)',
    quarantined_benchmarks_json STRING         COMMENT 'JSON: array of benchmarks removed by pre-evaluation quarantine ({question_id, reason_code, reason_detail, question})'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Evaluation iteration results - scores and failures per eval pass'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_PATCHES_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_patches (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL COMMENT 'Iteration when this patch was applied',
    lever               INT           NOT NULL COMMENT 'Lever number (1-5)',
    patch_index         INT           NOT NULL COMMENT 'Index within the patch set',
    patch_type          STRING        NOT NULL COMMENT 'Patch type from PATCH_TYPES',
    scope               STRING        NOT NULL COMMENT 'genie_config or uc_artifact or both',
    risk_level          STRING        NOT NULL COMMENT 'low|medium|high',
    target_object       STRING                 COMMENT 'Object being modified (table name, column name, etc.)',
    patch_json          STRING        NOT NULL COMMENT 'JSON: full patch definition',
    command_json        STRING                 COMMENT 'JSON: rendered action command',
    rollback_json       STRING                 COMMENT 'JSON: rollback command',
    applied_at          TIMESTAMP     NOT NULL COMMENT 'When the patch was applied',
    rolled_back         BOOLEAN                COMMENT 'True if this patch was subsequently rolled back',
    rolled_back_at      TIMESTAMP              COMMENT 'When the rollback occurred',
    rollback_reason     STRING                 COMMENT 'Why the patch was rolled back',
    proposal_id         STRING                 COMMENT 'FK to the proposal that generated this patch',
    cluster_id          STRING                 COMMENT 'Failure cluster that motivated this patch',
    provenance_json     STRING                 COMMENT 'JSON: full provenance chain from judge verdicts to this patch'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Patch audit trail - every metadata change applied to Genie Space'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_EVAL_ASI_RESULTS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_eval_asi_results (
    run_id              STRING        NOT NULL COMMENT 'Optimization run ID',
    mlflow_run_id       STRING                 COMMENT 'MLflow evaluation run ID (for trace linking)',
    iteration           INT           NOT NULL COMMENT 'Evaluation iteration number',
    question_id         STRING        NOT NULL COMMENT 'Benchmark question ID',
    judge               STRING        NOT NULL COMMENT 'Judge name',
    value               STRING        NOT NULL COMMENT 'Judge verdict (yes|no|skipped|genie_correct|...)',
    failure_type        STRING                 COMMENT 'From FAILURE_TAXONOMY',
    severity            STRING                 COMMENT 'critical|major|minor|info',
    confidence          DOUBLE                 COMMENT 'Judge confidence (0.0-1.0)',
    blame_set           STRING                 COMMENT 'JSON: array of metadata fields blamed',
    counterfactual_fix  STRING                 COMMENT 'Suggested metadata change to fix the issue',
    wrong_clause        STRING                 COMMENT 'SQL clause that is wrong',
    expected_value      STRING                 COMMENT 'What the correct value should be',
    actual_value        STRING                 COMMENT 'What Genie actually produced',
    missing_metadata    STRING                 COMMENT 'What metadata should exist but does not',
    ambiguity_detected  BOOLEAN                COMMENT 'True if the question is ambiguous',
    logged_at           TIMESTAMP     NOT NULL COMMENT 'When this ASI row was written'
)
USING DELTA
COMMENT 'Actionable Side Information from evaluation judges'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_DATA_ACCESS_GRANTS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_data_access_grants (
    grant_id            STRING        NOT NULL COMMENT 'UUID for this grant record',
    target_catalog      STRING        NOT NULL COMMENT 'Catalog the SP was granted access to',
    target_schema       STRING        NOT NULL COMMENT 'Schema the SP was granted access to',
    granted_by          STRING        NOT NULL COMMENT 'User who performed the grant',
    granted_at          TIMESTAMP     NOT NULL COMMENT 'When the grant was applied',
    revoked_at          TIMESTAMP              COMMENT 'When the grant was revoked (null if active)',
    status              STRING        NOT NULL COMMENT 'active|revoked',
    grant_type          STRING        NOT NULL COMMENT 'read|write — read grants SELECT/EXECUTE, write adds MODIFY'
)
USING DELTA
COMMENT 'Tracks UC privileges granted to the app SP for accessing Genie space assets'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_PROVENANCE_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_provenance (
    run_id              STRING        NOT NULL  COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL  COMMENT 'Lever loop iteration',
    lever               INT           NOT NULL  COMMENT 'Lever number (1-5)',
    question_id         STRING        NOT NULL  COMMENT 'Benchmark question ID',
    signal_type         STRING        NOT NULL  COMMENT 'hard or soft',
    arbiter_verdict     STRING                  COMMENT 'Arbiter verdict for this question',
    judge               STRING        NOT NULL  COMMENT 'Judge that failed',
    judge_verdict       STRING        NOT NULL  COMMENT 'Judge verdict (PASS/FAIL)',
    asi_failure_type_raw STRING                 COMMENT 'Raw failure_type from ASI metadata',
    resolved_root_cause STRING        NOT NULL  COMMENT 'Final root cause after resolution chain',
    resolution_method   STRING        NOT NULL  COMMENT 'asi_metadata or rationale_pattern or sql_diff',
    blame_set           STRING                  COMMENT 'JSON array of blamed objects',
    counterfactual_fix  STRING                  COMMENT 'Suggested fix from judge',
    wrong_clause        STRING                  COMMENT 'SQL clause identified as wrong',
    rationale_snippet   STRING                  COMMENT 'First 500 chars of judge rationale',
    expected_sql        STRING                  COMMENT 'Expected SQL (first 2000 chars)',
    generated_sql       STRING                  COMMENT 'Generated SQL (first 2000 chars)',
    cluster_id          STRING        NOT NULL  COMMENT 'Cluster this question was grouped into',
    proposal_id         STRING                  COMMENT 'Proposal generated from this cluster',
    patch_type          STRING                  COMMENT 'Type of patch applied',
    gate_type           STRING                  COMMENT 'slice or p0 or full',
    gate_result         STRING                  COMMENT 'pass or fail or rollback',
    gate_regression     STRING                  COMMENT 'JSON regression details if gate failed',
    logged_at           TIMESTAMP     NOT NULL  COMMENT 'When this row was written'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'End-to-end provenance: links every patch to originating judge verdicts and gate outcomes'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

_GENIE_OPT_SUGGESTIONS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_suggestions (
    suggestion_id       STRING        NOT NULL COMMENT 'UUID for this suggestion',
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    space_id            STRING        NOT NULL COMMENT 'Genie Space ID',
    iteration           INT                    COMMENT 'Lever-loop iteration that produced this suggestion',
    lever               INT                    COMMENT 'Lever number that produced this suggestion',
    type                STRING        NOT NULL COMMENT 'METRIC_VIEW | FUNCTION',
    title               STRING        NOT NULL COMMENT 'Short human-readable title',
    rationale           STRING                 COMMENT 'Why the strategist proposed this',
    definition          STRING                 COMMENT 'SQL or pseudocode definition',
    affected_questions  STRING                 COMMENT 'JSON array of question IDs that would benefit',
    estimated_impact    STRING                 COMMENT 'Estimated accuracy improvement description',
    status              STRING        NOT NULL COMMENT 'PROPOSED | ACCEPTED | REJECTED | IMPLEMENTED',
    reviewed_by         STRING                 COMMENT 'User who reviewed the suggestion',
    reviewed_at         TIMESTAMP              COMMENT 'When the suggestion was reviewed',
    created_at          TIMESTAMP     NOT NULL COMMENT 'When the suggestion was created',
    updated_at          TIMESTAMP     NOT NULL COMMENT 'Last update timestamp'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Strategist improvement suggestions — proposed metric views and functions for human review'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.enableChangeDataFeed' = 'true'
)"""

# ── Combined DDL dict ────────────────────────────────────────────────────

_ALL_DDL: dict[str, str] = {
    TABLE_RUNS: _GENIE_OPT_RUNS_DDL,
    TABLE_STAGES: _GENIE_OPT_STAGES_DDL,
    TABLE_ITERATIONS: _GENIE_OPT_ITERATIONS_DDL,
    TABLE_PATCHES: _GENIE_OPT_PATCHES_DDL,
    TABLE_ASI: _GENIE_EVAL_ASI_RESULTS_DDL,
    TABLE_DATA_ACCESS_GRANTS: _GENIE_OPT_DATA_ACCESS_GRANTS_DDL,
    TABLE_PROVENANCE: _GENIE_OPT_PROVENANCE_DDL,
    TABLE_SUGGESTIONS: _GENIE_OPT_SUGGESTIONS_DDL,
}
