"""Lever-5 forced-structural-synthesis dispatch — extracted from harness.py.

This module exists so the L5 forced-synthesis dispatch (formerly inline
at harness.py:22720-22929) is callable in isolation. The replay harness
calls this function with a stubbed ``synthesize`` callable to verify
dispatch behavior offline against frozen fixtures, without spinning up
the full optimizer.

The function preserves the EXACT behavior of the inline block — including
the label-divergence bug where ``_LEVER5_GATE_DROPS[*].root_causes`` (which
prefers ``asi_failure_type``) is compared with strict equality against
``cluster.root_cause`` (which is the RcaKind label). Fixing that bug is
Plan A's job, not this refactor's.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from typing import Any, Callable


def cluster_failure_keys(cluster: Any) -> tuple[str, ...]:
    """Return the canonical set of failure-label keys for a cluster.

    Bridges the label divergence between the older ``asi_failure_type``
    classification and the newer ``root_cause`` RcaKind label. The
    structural-gate ledger at ``optimizer.py:15346-15350`` stores
    ``_LEVER5_GATE_DROPS[*].root_causes`` preferring ``asi_failure_type``;
    the dispatch loop reads the cluster's ``root_cause``. When the two
    labels disagree, strict equality silently drops the cluster.

    This helper returns BOTH labels (asi_failure_type first, then
    root_cause), de-duplicated and with empties / non-strings filtered
    out. The dispatch loop uses ``_rc in cluster_failure_keys(cand)``
    instead of ``cand.get("root_cause") == _rc``.

    Order matters: ``asi_failure_type`` is listed first to match the
    write-side preference at ``optimizer.py:15346-15350``. Code that
    needs a single "canonical" key (rare) can take the first element.

    Robust to:
      - ``None`` / non-dict input (returns ``()``)
      - missing / empty / non-string label values (filtered out)
      - aligned labels (de-duplicated to one entry)
    """
    if not isinstance(cluster, dict):
        return ()
    out: list[str] = []
    for key in ("asi_failure_type", "root_cause"):
        raw = cluster.get(key)
        if raw is None:
            continue
        s = str(raw).strip()
        if not s:
            continue
        if s not in out:
            out.append(s)
    return tuple(out)


# Patch types that count as a "lever-5 emitted proposal" for the
# safety-net predicate. Mirrors harness.py's classification of
# add_example_sql / update_example_sql as the L5 patch family.
_L5_PATCH_TYPES: frozenset[str] = frozenset({
    "add_example_sql",
    "update_example_sql",
})


def _should_invoke_safety_net(
    *,
    ag: Mapping[str, Any],
    l5_ag_drops: Sequence[Mapping[str, Any]],
    iter_source_clusters_by_id: Mapping[str, Mapping[str, Any]],
    ag_proposals_so_far: Sequence[Mapping[str, Any]],
) -> list[tuple[str, str]]:
    """Return the list of ``(cluster_id, failure_key)`` triggers for which
    the rich-path safety net should fire.

    The safety net is the Plan A Part 2 complement to the gate-drop
    dispatch. It fires when ALL these hold:

      1. ``l5_ag_drops`` is empty — the structural gate did not fire for
         this AG, so the existing label-canonical dispatch will not run.
      2. Lever 5 emitted zero proposals for this AG — no
         ``add_example_sql`` or ``update_example_sql`` patches exist in
         ``ag_proposals_so_far``. (Counts patches generated by lever 5
         regardless of which strategy lever they were attributed to;
         the patch_type is the source of truth.)
      3. At least one source cluster has a failure label
         (``asi_failure_type`` or ``root_cause``) in
         ``_SQL_SHAPE_ROOT_CAUSES``.

    Returns a list because an AG can have multiple SQL-shape source
    clusters. Caller iterates the list and calls ``synthesize`` per
    trigger. Order matches ``ag.source_cluster_ids``.

    Empty list = predicate didn't fire.
    """
    if l5_ag_drops:
        return []
    for proposal in (ag_proposals_so_far or ()):
        if not isinstance(proposal, Mapping):
            continue
        if str(proposal.get("patch_type") or "") in _L5_PATCH_TYPES:
            return []

    # Lazy import to avoid a hard module-level coupling to optimizer.py.
    from genie_space_optimizer.optimization.optimizer import (
        _SQL_SHAPE_ROOT_CAUSES,
    )

    triggers: list[tuple[str, str]] = []
    for cid in (ag.get("source_cluster_ids") or ()):
        cluster = iter_source_clusters_by_id.get(str(cid))
        if not isinstance(cluster, Mapping):
            continue
        for key in cluster_failure_keys(cluster):
            if key in _SQL_SHAPE_ROOT_CAUSES:
                triggers.append((str(cid), key))
                break  # one trigger per cluster (the first SQL-shape match)
    return triggers


@dataclass(frozen=True)
class ForcedSynthesisDispatchResult:
    """Per-call result of ``dispatch_forced_structural_synthesis``.

    Fields:
        attempted_dispatches: tuple of ``(cluster_id, root_cause)`` pairs
            the dispatch loop actually visited (i.e., where
            ``_should_force_structural_synthesis`` returned True AND a
            matching cluster was found in ``iter_source_clusters_by_id``).
            Empty when the label-divergence bug short-circuits the loop.
        appended_proposals: tuple of forced ``add_example_sql`` proposal
            dicts produced by successful synthesis. The harness appends
            these to ``all_proposals`` at the call site.
        emitted_decision_records: tuple of ``DecisionRecord.to_dict()``
            outputs for ``NO_STRUCTURAL_CANDIDATE`` cases. The harness
            extends ``_current_iter_inputs["decision_records"]`` with
            these at the call site.

    Exceptions are NOT caught inside the dispatch function — the harness
    call site's existing outer try-except handles them (same shape as
    the original inline block). This preserves byte-stable exception
    accounting via ``_phase_b_producer_exceptions``.
    """
    attempted_dispatches: tuple[tuple[str, str], ...]
    appended_proposals: tuple[dict[str, Any], ...]
    emitted_decision_records: tuple[dict[str, Any], ...]


def dispatch_forced_structural_synthesis(
    *,
    run_id: str,
    iteration: int,
    ag: Mapping[str, Any],
    l5_ag_drops: Sequence[Mapping[str, Any]],
    iter_source_clusters_by_id: Mapping[str, Mapping[str, Any]],
    iter_rca_id_by_cluster: Mapping[str, str],
    metadata_snapshot: Mapping[str, Any],
    benchmarks: Sequence[Mapping[str, Any]],
    catalog: str,
    schema: str,
    w: Any,
    spark: Any,
    lever_keys: Iterable[int],
    reflection_buffer: Sequence[Any],
    current_iter_inputs: dict[str, Any],
    ag_proposals_so_far: Sequence[Mapping[str, Any]] = (),
    synthesize: Callable[..., Any] | None = None,
) -> ForcedSynthesisDispatchResult:
    """Run the L5 forced-structural-synthesis dispatch for one AG.

    Parameters mirror the closure-of-locals pinned in Task 0. The
    ``synthesize`` parameter defaults to
    ``run_cluster_driven_synthesis_for_single_cluster`` from
    ``cluster_driven_synthesis`` (resolved lazily inside the function
    to avoid circular imports); tests pass a stub.

    Returns a ``ForcedSynthesisDispatchResult`` instead of mutating the
    caller's locals directly. The harness call site applies the side
    effects (append to ``all_proposals``, extend
    ``_current_iter_inputs["decision_records"]``, bump
    ``_phase_b_producer_exceptions``).

    BUG PRESERVED — the strict-equality cluster lookup at the inner
    ``for _cid in _drop.get("source_clusters")`` loop matches
    ``cluster.root_cause`` against ``_drop.root_causes[*]``. The latter
    prefers ``asi_failure_type`` (per optimizer.py:15338-15342), so
    SQL-shape clusters whose ``asi_failure_type`` differs from their
    RcaKind ``root_cause`` are silently skipped. Plan A fixes this; this
    refactor only moves the bug into a place where it is testable.
    """
    import logging
    logger = logging.getLogger(__name__)

    attempted: list[tuple[str, str]] = []
    appended: list[dict[str, Any]] = []
    emitted: list[dict[str, Any]] = []

    if not l5_ag_drops:
        return ForcedSynthesisDispatchResult(
            attempted_dispatches=(),
            appended_proposals=(),
            emitted_decision_records=(),
        )

    # Resolve the synthesize callable lazily to avoid circular imports.
    if synthesize is None:
        from genie_space_optimizer.optimization.cluster_driven_synthesis import (
            run_cluster_driven_synthesis_for_single_cluster as _default_synth,
        )
        synthesize = _default_synth

    from genie_space_optimizer.optimization.decision_emitters import (
        no_structural_candidate_record,
    )
    from genie_space_optimizer.optimization.harness import (
        _should_force_structural_synthesis,
    )
    from genie_space_optimizer.common.warehouse import (
        resolve_warehouse_id,
    )

    ag_id = str(ag.get("id") or "")
    # _l5_ag_rca_id is precomputed by the harness's earlier block at
    # 22650-22691; we recompute it here so the function is callable in
    # isolation.
    _l5_ag_rca_id = ""
    for _cid in (ag.get("source_cluster_ids") or []):
        _l5_ag_rca_id = str(iter_rca_id_by_cluster.get(str(_cid)) or "")
        if _l5_ag_rca_id:
            break

    for _drop in l5_ag_drops:
        _drop_cluster: dict | None = None
        _drop_root_cause = ""
        for _rc in (_drop.get("root_causes") or ()):
            if not _should_force_structural_synthesis(
                gate_drop_reason=(
                    "lever5_structural_sql_shape_no_example_sql"
                ),
                cluster_root_cause=str(_rc),
            ):
                continue
            for _cid in (_drop.get("source_clusters") or ()):
                _cand = iter_source_clusters_by_id.get(str(_cid))
                # Plan A Part 1 — canonicalized lookup. ``_rc`` came
                # from ``_LEVER5_GATE_DROPS[*].root_causes`` which
                # prefers ``asi_failure_type`` (per
                # ``optimizer.py:15346-15350``). The cluster carries
                # both ``asi_failure_type`` and ``root_cause`` (the
                # RcaKind label). ``cluster_failure_keys`` returns
                # both, so set-membership matches whichever the
                # ledger picked. See
                # ``docs/prompt_improvements/2026-05-16-plan-a-canonicalize-label-key.md``.
                if isinstance(_cand, dict) and str(_rc) in cluster_failure_keys(_cand):
                    _drop_cluster = dict(_cand)
                    _drop_root_cause = str(_rc)
                    break
            if _drop_cluster is not None:
                break
        if _drop_cluster is None:
            continue

        attempted.append(
            (str(_drop_cluster.get("cluster_id") or ""), _drop_root_cause)
        )

        _synth_result = synthesize(
            _drop_cluster,
            metadata_snapshot,
            benchmarks=benchmarks,
            catalog=catalog,
            gold_schema=schema,
            warehouse_id=resolve_warehouse_id(""),
            w=w,
            spark=spark,
        )
        if _synth_result.proposal is not None:
            _sp = _synth_result.proposal
            _forced_proposal = {
                "proposal_id": f"P{len(appended) + 1:03d}_FORCED",
                "cluster_id": f"{ag_id}_FORCED_SYN",
                "lever": 5,
                "scope": "genie_config",
                "patch_type": "add_example_sql",
                "change_description": (
                    f"[{ag_id}] Forced structural synthesis: "
                    f"{str(_sp.get('example_question', ''))[:80]}"
                ),
                "proposed_value": _sp.get("example_question", ""),
                "example_question": _sp.get("example_question", ""),
                "example_sql": _sp.get("example_sql", ""),
                "parameters": _sp.get("parameters", []) or [],
                "usage_guidance": _sp.get("usage_guidance", ""),
                "rationale": (
                    f"Forced structural synthesis at L5 gate "
                    f"drop (archetype="
                    f"{_sp.get('_archetype_name', '?')}). "
                    f"Root cause: {_drop_root_cause}."
                ),
                "confidence": 0.85,
                "questions_fixed": 1,
                "questions_at_risk": 0,
                "net_impact": 0.85,
                "kit_id": _sp.get("kit_id", ""),
                "target_qids": _sp.get("target_qids", []),
                "rca_id": _sp.get("rca_id", ""),
                "_archetype_name": _sp.get("_archetype_name", ""),
                "_cluster_id": _sp.get("_cluster_id", ""),
                "provenance": {
                    "synthesis_source": "forced_lever5_drop",
                    "drop_root_cause": _drop_root_cause,
                    "kit_id": _sp.get("kit_id", ""),
                    "target_qids": _sp.get("target_qids", []),
                },
            }
            appended.append(_forced_proposal)
            logger.info(
                "forced structural synthesis succeeded for AG=%s "
                "root_cause=%s archetype=%s",
                ag_id, _drop_root_cause,
                _sp.get("_archetype_name", "?"),
            )
        else:
            _nsc = no_structural_candidate_record(
                run_id=run_id,
                iteration=iteration,
                ag_id=str(ag_id),
                cluster_id=str(
                    _drop_cluster.get("cluster_id") or ""
                ),
                rca_id=_l5_ag_rca_id,
                root_cause=_drop_root_cause,
                target_qids=tuple(
                    str(q) for q in (
                        ag.get("affected_questions") or []
                    )
                    if str(q)
                ),
                attempted_archetypes=(
                    _synth_result.attempted_archetypes
                ),
            )
            emitted.append(_nsc.to_dict())
            logger.info(
                "forced structural synthesis produced no candidate "
                "for AG=%s root_cause=%s skipped=%s archetypes=%s",
                ag_id, _drop_root_cause,
                _synth_result.skipped_reason,
                _synth_result.attempted_archetypes,
            )

    return ForcedSynthesisDispatchResult(
        attempted_dispatches=tuple(attempted),
        appended_proposals=tuple(appended),
        emitted_decision_records=tuple(emitted),
    )
