"""Lever-5 forced-structural-synthesis dispatch — extracted from harness.py.

This module exists so the L5 forced-synthesis dispatch (formerly inline
at harness.py:22720-22929) is callable in isolation. The replay harness
calls this function with a stubbed ``synthesize`` callable to verify
dispatch behavior offline against frozen fixtures, without spinning up
the full optimizer.

The function preserves the EXACT behavior of the inline block — including
the label-divergence bug where ``_LEVER5_GATE_DROPS[*].root_causes`` (which
prefers ``asi_failure_type``) is compared with strict equality against
``cluster.root_cause`` (which is the RcaKind label). Fixing that bug is
Plan A's job, not this refactor's.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from typing import Any, Callable


def cluster_failure_keys(cluster: Any) -> tuple[str, ...]:
    """Return the canonical set of failure-label keys for a cluster.

    Bridges the label divergence between the older ``asi_failure_type``
    classification and the newer ``root_cause`` RcaKind label. The
    structural-gate ledger at ``optimizer.py:15346-15350`` stores
    ``_LEVER5_GATE_DROPS[*].root_causes`` preferring ``asi_failure_type``;
    the dispatch loop reads the cluster's ``root_cause``. When the two
    labels disagree, strict equality silently drops the cluster.

    This helper returns BOTH labels (asi_failure_type first, then
    root_cause), de-duplicated and with empties / non-strings filtered
    out. The dispatch loop uses ``_rc in cluster_failure_keys(cand)``
    instead of ``cand.get("root_cause") == _rc``.

    Order matters: ``asi_failure_type`` is listed first to match the
    write-side preference at ``optimizer.py:15346-15350``. Code that
    needs a single "canonical" key (rare) can take the first element.

    Robust to:
      - ``None`` / non-dict input (returns ``()``)
      - missing / empty / non-string label values (filtered out)
      - aligned labels (de-duplicated to one entry)
    """
    if not isinstance(cluster, dict):
        return ()
    out: list[str] = []
    for key in ("asi_failure_type", "root_cause"):
        raw = cluster.get(key)
        if raw is None:
            continue
        s = str(raw).strip()
        if not s:
            continue
        if s not in out:
            out.append(s)
    return tuple(out)


# Patch types that count as a "lever-5 emitted proposal" for the
# safety-net predicate. Mirrors harness.py's classification of
# add_example_sql / update_example_sql as the L5 patch family.
_L5_PATCH_TYPES: frozenset[str] = frozenset({
    "add_example_sql",
    "update_example_sql",
})


def _should_invoke_safety_net(
    *,
    ag: Mapping[str, Any],
    l5_ag_drops: Sequence[Mapping[str, Any]],
    iter_source_clusters_by_id: Mapping[str, Mapping[str, Any]],
    ag_proposals_so_far: Sequence[Mapping[str, Any]],
) -> list[tuple[str, str]]:
    """Return the list of ``(cluster_id, failure_key)`` triggers for which
    the rich-path safety net should fire.

    The safety net is the Plan A Part 2 complement to the gate-drop
    dispatch. It fires when ALL these hold:

      1. ``l5_ag_drops`` is empty — the structural gate did not fire for
         this AG, so the existing label-canonical dispatch will not run.
      2. Lever 5 emitted zero proposals for this AG — no
         ``add_example_sql`` or ``update_example_sql`` patches exist in
         ``ag_proposals_so_far``. (Counts patches generated by lever 5
         regardless of which strategy lever they were attributed to;
         the patch_type is the source of truth.)
      3. At least one source cluster has a failure label
         (``asi_failure_type`` or ``root_cause``) in
         ``_SQL_SHAPE_ROOT_CAUSES``.

    Returns a list because an AG can have multiple SQL-shape source
    clusters. Caller iterates the list and calls ``synthesize`` per
    trigger. Order matches ``ag.source_cluster_ids``.

    Empty list = predicate didn't fire.
    """
    if l5_ag_drops:
        return []
    for proposal in (ag_proposals_so_far or ()):
        if not isinstance(proposal, Mapping):
            continue
        if str(proposal.get("patch_type") or "") in _L5_PATCH_TYPES:
            return []

    # Lazy import to avoid a hard module-level coupling to optimizer.py.
    from genie_space_optimizer.optimization.optimizer import (
        _SQL_SHAPE_ROOT_CAUSES,
    )

    triggers: list[tuple[str, str]] = []
    for cid in (ag.get("source_cluster_ids") or ()):
        cluster = iter_source_clusters_by_id.get(str(cid))
        if not isinstance(cluster, Mapping):
            continue
        for key in cluster_failure_keys(cluster):
            if key in _SQL_SHAPE_ROOT_CAUSES:
                triggers.append((str(cid), key))
                break  # one trigger per cluster (the first SQL-shape match)
    return triggers


# Plan B — observability counter for whether the Plan A trapdoor still
# matters once Plan B is on by default. We expect this to drop near zero
# in production; if it does, a follow-up PR can remove the trapdoor.
# A non-zero value indicates the trapdoor caught a case Plan B missed
# (e.g., Stage-1 picked L5a-only and the structural gate dropped it,
# OR Stage-1 didn't pick L5 at all but a cluster is SQL-shape).
_FORCED_SYNTHESIS_TRAPDOOR_INVOCATIONS: int = 0


def get_forced_synthesis_trapdoor_invocations() -> int:
    """Return the count of trapdoor dispatches since the last reset.

    Increments whenever ``dispatch_forced_structural_synthesis`` actually
    calls ``synthesize`` (either the gate-drop path or the safety-net
    path). Stays at zero when no L5 drops + no safety-net triggers.
    """
    return _FORCED_SYNTHESIS_TRAPDOOR_INVOCATIONS


def reset_forced_synthesis_trapdoor_invocations() -> None:
    """Reset the counter to zero. Tests call this in setup; production
    code does not call it (the counter accumulates across the run).
    """
    global _FORCED_SYNTHESIS_TRAPDOOR_INVOCATIONS
    _FORCED_SYNTHESIS_TRAPDOOR_INVOCATIONS = 0


@dataclass(frozen=True)
class ForcedSynthesisDispatchResult:
    """Per-call result of ``dispatch_forced_structural_synthesis``.

    Fields:
        attempted_dispatches: tuple of ``(cluster_id, root_cause)`` pairs
            the dispatch loop actually visited (i.e., where
            ``_should_force_structural_synthesis`` returned True AND a
            matching cluster was found in ``iter_source_clusters_by_id``).
            Empty when the label-divergence bug short-circuits the loop.
        appended_proposals: tuple of forced ``add_example_sql`` proposal
            dicts produced by successful synthesis. The harness appends
            these to ``all_proposals`` at the call site.
        emitted_decision_records: tuple of ``DecisionRecord.to_dict()``
            outputs for ``NO_STRUCTURAL_CANDIDATE`` cases. The harness
            extends ``_current_iter_inputs["decision_records"]`` with
            these at the call site.

    Exceptions are NOT caught inside the dispatch function — the harness
    call site's existing outer try-except handles them (same shape as
    the original inline block). This preserves byte-stable exception
    accounting via ``_phase_b_producer_exceptions``.
    """
    attempted_dispatches: tuple[tuple[str, str], ...]
    appended_proposals: tuple[dict[str, Any], ...]
    emitted_decision_records: tuple[dict[str, Any], ...]


def _cluster_is_grounded(cluster: Mapping) -> bool:
    """Phase 0.3 (2026-05-17) — a cluster is grounded for synthesis
    iff it carries a non-empty ``rca_card`` payload.

    Matches the predicate in
    :func:`harness.collect_blocked_clusters` and
    ``invariants.check_i7_rca_grounding``. Centralising it here lets
    the synthesis dispatcher refuse ungrounded clusters at entry,
    instead of invoking the synthesizer and returning empty
    archetypes silently.
    """
    if not isinstance(cluster, Mapping):
        return False
    rca_card = cluster.get("rca_card")
    if isinstance(rca_card, Mapping) and rca_card:
        return True
    return bool(rca_card)


def dispatch_forced_structural_synthesis(
    *,
    run_id: str,
    iteration: int,
    ag: Mapping[str, Any],
    l5_ag_drops: Sequence[Mapping[str, Any]],
    iter_source_clusters_by_id: Mapping[str, Mapping[str, Any]],
    iter_rca_id_by_cluster: Mapping[str, str],
    metadata_snapshot: Mapping[str, Any],
    benchmarks: Sequence[Mapping[str, Any]],
    catalog: str,
    schema: str,
    w: Any,
    spark: Any,
    lever_keys: Iterable[int],
    reflection_buffer: Sequence[Any],
    current_iter_inputs: dict[str, Any],
    ag_proposals_so_far: Sequence[Mapping[str, Any]] = (),
    synthesize: Callable[..., Any] | None = None,
) -> ForcedSynthesisDispatchResult:
    """Run the L5 forced-structural-synthesis dispatch for one AG.

    Parameters mirror the closure-of-locals pinned in Task 0. The
    ``synthesize`` parameter defaults to
    ``run_cluster_driven_synthesis_for_single_cluster`` from
    ``cluster_driven_synthesis`` (resolved lazily inside the function
    to avoid circular imports); tests pass a stub.

    Returns a ``ForcedSynthesisDispatchResult`` instead of mutating the
    caller's locals directly. The harness call site applies the side
    effects (append to ``all_proposals``, extend
    ``_current_iter_inputs["decision_records"]``, bump
    ``_phase_b_producer_exceptions``).

    BUG PRESERVED — the strict-equality cluster lookup at the inner
    ``for _cid in _drop.get("source_clusters")`` loop matches
    ``cluster.root_cause`` against ``_drop.root_causes[*]``. The latter
    prefers ``asi_failure_type`` (per optimizer.py:15338-15342), so
    SQL-shape clusters whose ``asi_failure_type`` differs from their
    RcaKind ``root_cause`` are silently skipped. Plan A fixes this; this
    refactor only moves the bug into a place where it is testable.
    """
    import logging
    logger = logging.getLogger(__name__)

    global _FORCED_SYNTHESIS_TRAPDOOR_INVOCATIONS

    attempted: list[tuple[str, str]] = []
    appended: list[dict[str, Any]] = []
    emitted: list[dict[str, Any]] = []

    # Resolve the synthesize callable lazily to avoid circular imports.
    if synthesize is None:
        from genie_space_optimizer.optimization.cluster_driven_synthesis import (
            run_cluster_driven_synthesis_for_single_cluster as _default_synth,
        )
        synthesize = _default_synth

    from genie_space_optimizer.optimization.decision_emitters import (
        no_structural_candidate_record,
    )
    from genie_space_optimizer.optimization.harness import (
        _should_force_structural_synthesis,
    )
    from genie_space_optimizer.common.warehouse import (
        resolve_warehouse_id,
    )

    ag_id = str(ag.get("id") or "")
    # Phase 3 (2026-05-17) — advance tape-replay binding to this AG.
    # ``_tape_binding_set_ag`` is a no-op in production (the default
    # ``_TAPE_BINDING_HOOK`` is a no-op); replay tests patch it to
    # update the active ``TapeCallContext`` so subsequent
    # ``cluster_driven_synthesis`` LLM lookups resolve under the
    # right ``(ag_id, cluster_id)`` key.
    from genie_space_optimizer.optimization.harness import (
        _tape_binding_set_ag,
    )
    _primary_cluster_id_for_tape = ""
    _src_cluster_ids_for_tape = ag.get("source_cluster_ids") or []
    if _src_cluster_ids_for_tape:
        _primary_cluster_id_for_tape = str(_src_cluster_ids_for_tape[0] or "")
    _tape_binding_set_ag(
        ag_id,
        cluster_id=_primary_cluster_id_for_tape,
    )
    # _l5_ag_rca_id is precomputed by the harness's earlier block at
    # 22650-22691; we recompute it here so the function is callable in
    # isolation.
    _l5_ag_rca_id = ""
    for _cid in (ag.get("source_cluster_ids") or []):
        _l5_ag_rca_id = str(iter_rca_id_by_cluster.get(str(_cid)) or "")
        if _l5_ag_rca_id:
            break

    for _drop in l5_ag_drops:
        _drop_cluster: dict | None = None
        _drop_root_cause = ""
        for _rc in (_drop.get("root_causes") or ()):
            if not _should_force_structural_synthesis(
                gate_drop_reason=(
                    "lever5_structural_sql_shape_no_example_sql"
                ),
                cluster_root_cause=str(_rc),
            ):
                continue
            for _cid in (_drop.get("source_clusters") or ()):
                _cand = iter_source_clusters_by_id.get(str(_cid))
                # Plan A Part 1 — canonicalized lookup. ``_rc`` came
                # from ``_LEVER5_GATE_DROPS[*].root_causes`` which
                # prefers ``asi_failure_type`` (per
                # ``optimizer.py:15346-15350``). The cluster carries
                # both ``asi_failure_type`` and ``root_cause`` (the
                # RcaKind label). ``cluster_failure_keys`` returns
                # both, so set-membership matches whichever the
                # ledger picked. See
                # ``docs/prompt_improvements/2026-05-16-plan-a-canonicalize-label-key.md``.
                if isinstance(_cand, dict) and str(_rc) in cluster_failure_keys(_cand):
                    _drop_cluster = dict(_cand)
                    _drop_root_cause = str(_rc)
                    break
            if _drop_cluster is not None:
                break
        if _drop_cluster is None:
            continue

        attempted.append(
            (str(_drop_cluster.get("cluster_id") or ""), _drop_root_cause)
        )

        # Phase 0.3 (2026-05-17) — refuse ungrounded clusters BEFORE
        # invoking the synthesizer. Two live runs (airline 59a173d3,
        # 7now ab65fefe) reported I7
        # ``open_cluster_ungrounded_at_ag_emit`` 48 times; the
        # synthesizer was then called and returned empty
        # (attempted_archetypes=[]). Emit a typed
        # ``missing_rca_card`` decline and skip the synthesize call.
        if not _cluster_is_grounded(_drop_cluster):
            _nsc = no_structural_candidate_record(
                run_id=run_id,
                iteration=iteration,
                ag_id=str(ag_id),
                cluster_id=str(_drop_cluster.get("cluster_id") or ""),
                rca_id=_l5_ag_rca_id,
                root_cause=_drop_root_cause,
                target_qids=tuple(
                    str(q) for q in (
                        ag.get("affected_questions") or []
                    )
                    if str(q)
                ),
                attempted_archetypes=(),
                skipped_reason="missing_rca_card",
            )
            emitted.append(_nsc.to_dict())
            logger.info(
                "forced structural synthesis refused ungrounded "
                "cluster AG=%s cluster=%s root_cause=%s",
                ag_id, _drop_cluster.get("cluster_id"),
                _drop_root_cause,
            )
            continue

        _FORCED_SYNTHESIS_TRAPDOOR_INVOCATIONS += 1
        # Phase 1.3 (2026-05-17) — convert the legacy cluster + ag
        # dicts into a single typed FailureCluster at this boundary.
        # The synthesizer accepts both forms (Phase 1.2) but the
        # typed view is the canonical input going forward; building
        # it here also raises FailureClusterIdentityError if the
        # cluster/ag identity disagrees.
        from genie_space_optimizer.optimization.failure_cluster import (
            FailureCluster,
        )
        _failure_cluster = FailureCluster.from_legacy(_drop_cluster, ag=ag)
        _synth_result = synthesize(
            _failure_cluster,
            metadata_snapshot,
            benchmarks=benchmarks,
            catalog=catalog,
            gold_schema=schema,
            warehouse_id=resolve_warehouse_id(""),
            w=w,
            spark=spark,
        )
        if _synth_result.proposal is not None:
            _sp = _synth_result.proposal
            _forced_proposal = {
                "proposal_id": f"P{len(appended) + 1:03d}_FORCED",
                "cluster_id": f"{ag_id}_FORCED_SYN",
                "lever": 5,
                "scope": "genie_config",
                "patch_type": "add_example_sql",
                "change_description": (
                    f"[{ag_id}] Forced structural synthesis: "
                    f"{str(_sp.get('example_question', ''))[:80]}"
                ),
                "proposed_value": _sp.get("example_question", ""),
                "example_question": _sp.get("example_question", ""),
                "example_sql": _sp.get("example_sql", ""),
                "parameters": _sp.get("parameters", []) or [],
                "usage_guidance": _sp.get("usage_guidance", ""),
                "rationale": (
                    f"Forced structural synthesis at L5 gate "
                    f"drop (archetype="
                    f"{_sp.get('_archetype_name', '?')}). "
                    f"Root cause: {_drop_root_cause}."
                ),
                "confidence": 0.85,
                "questions_fixed": 1,
                "questions_at_risk": 0,
                "net_impact": 0.85,
                "kit_id": _sp.get("kit_id", ""),
                "target_qids": _sp.get("target_qids", []),
                "rca_id": _sp.get("rca_id", ""),
                "_archetype_name": _sp.get("_archetype_name", ""),
                "_cluster_id": _sp.get("_cluster_id", ""),
                "provenance": {
                    "synthesis_source": "forced_lever5_drop",
                    "drop_root_cause": _drop_root_cause,
                    "kit_id": _sp.get("kit_id", ""),
                    "target_qids": _sp.get("target_qids", []),
                },
            }
            appended.append(_forced_proposal)
            logger.info(
                "forced structural synthesis succeeded for AG=%s "
                "root_cause=%s archetype=%s",
                ag_id, _drop_root_cause,
                _sp.get("_archetype_name", "?"),
            )
        else:
            _nsc = no_structural_candidate_record(
                run_id=run_id,
                iteration=iteration,
                ag_id=str(ag_id),
                cluster_id=str(
                    _drop_cluster.get("cluster_id") or ""
                ),
                rca_id=_l5_ag_rca_id,
                root_cause=_drop_root_cause,
                target_qids=tuple(
                    str(q) for q in (
                        ag.get("affected_questions") or []
                    )
                    if str(q)
                ),
                attempted_archetypes=(
                    _synth_result.attempted_archetypes
                ),
                # Phase 0.2 (2026-05-17) — surface the typed
                # decline reason so postmortems can distinguish
                # no_archetype_or_slice / no_top_n_archetype /
                # validate_afs_rejected / format_afs_failed /
                # safety_cap:* / budget:* without log-scraping.
                skipped_reason=str(
                    _synth_result.skipped_reason or ""
                ),
            )
            emitted.append(_nsc.to_dict())
            logger.info(
                "forced structural synthesis produced no candidate "
                "for AG=%s root_cause=%s skipped=%s archetypes=%s",
                ag_id, _drop_root_cause,
                _synth_result.skipped_reason,
                _synth_result.attempted_archetypes,
            )

    # Plan A Part 2 — rich-path safety net for "L5 emitted zero proposals".
    # Fires when the gate-drop loop above did not run (l5_ag_drops empty)
    # AND lever 5 emitted no proposals for this AG AND a source cluster
    # has a SQL-shape failure label. Same synthesizer, same output shape;
    # provenance.synthesis_source identifies the originating path. The
    # predicate ``_should_invoke_safety_net`` returns at most one trigger
    # per source cluster; we dispatch each trigger independently and
    # accumulate proposals.
    safety_net_triggers = _should_invoke_safety_net(
        ag=ag,
        l5_ag_drops=l5_ag_drops,
        iter_source_clusters_by_id=iter_source_clusters_by_id,
        ag_proposals_so_far=ag_proposals_so_far,
    )
    for (cid, failure_key) in safety_net_triggers:
        cluster = iter_source_clusters_by_id.get(cid)
        if not isinstance(cluster, Mapping):
            continue
        attempted.append((str(cid), failure_key))

        # Phase 0.3 (2026-05-17) — same pre-flight as the gate-drop
        # branch above. Decomposed AGs reach the safety-net path
        # without an RCA card too; refuse them with a typed
        # ``missing_rca_card`` decline rather than calling
        # synthesize and getting empty archetypes silently.
        if not _cluster_is_grounded(cluster):
            _safety_net_rca_id = str(
                iter_rca_id_by_cluster.get(cid) or ""
            )
            _nsc = no_structural_candidate_record(
                run_id=run_id,
                iteration=iteration,
                ag_id=str(ag_id),
                cluster_id=str(cid),
                rca_id=_safety_net_rca_id,
                root_cause=failure_key,
                target_qids=tuple(
                    str(q) for q in (
                        ag.get("affected_questions") or []
                    )
                    if str(q)
                ),
                attempted_archetypes=(),
                skipped_reason="missing_rca_card",
            )
            emitted.append(_nsc.to_dict())
            logger.info(
                "rich-path safety net refused ungrounded cluster "
                "AG=%s cluster=%s failure_key=%s",
                ag_id, cid, failure_key,
            )
            continue

        _FORCED_SYNTHESIS_TRAPDOOR_INVOCATIONS += 1
        # Phase 1.3 (2026-05-17) — typed conversion at the safety-net
        # boundary mirrors the gate-drop branch above. Same identity
        # reconciliation rules apply.
        from genie_space_optimizer.optimization.failure_cluster import (
            FailureCluster,
        )
        _failure_cluster = FailureCluster.from_legacy(cluster, ag=ag)
        _synth_result = synthesize(
            _failure_cluster,
            metadata_snapshot,
            benchmarks=benchmarks,
            catalog=catalog,
            gold_schema=schema,
            warehouse_id=resolve_warehouse_id(""),
            w=w,
            spark=spark,
        )
        if _synth_result.proposal is not None:
            _sp = _synth_result.proposal
            _safety_net_proposal = {
                "proposal_id": f"P{len(appended) + 1:03d}_SAFETY_NET",
                "cluster_id": f"{ag_id}_SAFETY_NET_SYN",
                "lever": 5,
                "scope": "genie_config",
                "patch_type": "add_example_sql",
                "change_description": (
                    f"[{ag_id}] Rich-path safety net: "
                    f"{str(_sp.get('example_question', ''))[:80]}"
                ),
                "proposed_value": _sp.get("example_question", ""),
                "example_question": _sp.get("example_question", ""),
                "example_sql": _sp.get("example_sql", ""),
                "parameters": _sp.get("parameters", []) or [],
                "usage_guidance": _sp.get("usage_guidance", ""),
                "rationale": (
                    f"Rich-path safety net: lever 5 emitted zero proposals "
                    f"for an AG with SQL-shape failure key '{failure_key}' "
                    f"on cluster {cid} (archetype="
                    f"{_sp.get('_archetype_name', '?')})."
                ),
                "confidence": 0.85,
                "questions_fixed": 1,
                "questions_at_risk": 0,
                "net_impact": 0.85,
                "kit_id": _sp.get("kit_id", ""),
                "target_qids": _sp.get("target_qids", []),
                "rca_id": _sp.get("rca_id", ""),
                "_archetype_name": _sp.get("_archetype_name", ""),
                "_cluster_id": _sp.get("_cluster_id", ""),
                "provenance": {
                    "synthesis_source": "rich_path_safety_net",
                    "safety_net_failure_key": failure_key,
                    "kit_id": _sp.get("kit_id", ""),
                    "target_qids": _sp.get("target_qids", []),
                },
            }
            appended.append(_safety_net_proposal)
            logger.info(
                "rich-path safety net synthesized example_sql for AG=%s "
                "cluster=%s failure_key=%s archetype=%s",
                ag_id, cid, failure_key,
                _sp.get("_archetype_name", "?"),
            )
        else:
            _safety_net_rca_id = str(
                iter_rca_id_by_cluster.get(cid) or ""
            )
            _nsc = no_structural_candidate_record(
                run_id=run_id,
                iteration=iteration,
                ag_id=str(ag_id),
                cluster_id=str(cid),
                rca_id=_safety_net_rca_id,
                root_cause=failure_key,
                target_qids=tuple(
                    str(q) for q in (
                        ag.get("affected_questions") or []
                    )
                    if str(q)
                ),
                attempted_archetypes=_synth_result.attempted_archetypes,
                # Phase 0.2 (2026-05-17) — surface the typed
                # decline reason for the safety-net (no-L5-drop
                # SQL-shape) branch so postmortems see the same
                # vocabulary as the gate-drop branch.
                skipped_reason=str(
                    _synth_result.skipped_reason or ""
                ),
            )
            emitted.append(_nsc.to_dict())
            logger.info(
                "rich-path safety net produced no candidate for AG=%s "
                "cluster=%s failure_key=%s skipped=%s archetypes=%s",
                ag_id, cid, failure_key,
                _synth_result.skipped_reason,
                _synth_result.attempted_archetypes,
            )

    return ForcedSynthesisDispatchResult(
        attempted_dispatches=tuple(attempted),
        appended_proposals=tuple(appended),
        emitted_decision_records=tuple(emitted),
    )
